<a href="https://colab.research.google.com/github/jfcoderx/Data-Sciense/blob/main/2_1_2_Universal_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Universal funksiyalar

In [1]:
import numpy as np

### unary funksiyalar - bitta argument qabul qiluvchi funksiya
sqrt, square, exp, log, modf, sign, isnan

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

sqrt massivning xar bir elementini kvadrat ildiizni qaytaradi

In [3]:
np.sqrt(arr) # arr massivni barcha elementini ilidinzi qaytaradi

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

2 argument uzatadigan bolsak xatolik chiqaradi

square nassuvning xar bir elementini kvadratga oshiradi

In [5]:
np.square(arr) # arr nomli barcha elementlarini kvadratga oshiradi

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

exp - massiv har bir elementini eksponentlaydi

In [6]:
np.exp(arr) # arr massivni barcha elementlarini eksponentini qaytaradi

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [7]:
np.log(arr) # arr nomli massivning barcha elementlarini logarifmini hisoblaydi

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

azgina xatolik korsatdi, -inf yani -infinite, sababi nol dan logarifm olish holati, tuzatish uchun

In [8]:
np.log(arr[1:])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

modf - bu funksiya haqiqiy sonlarni butun va qoldiq qismlarni ajratib beruvchi funksiya, agar massivimiz haqiqy sonlar bolganda bir massivga butun qismi, ikkinchi massivga kasr qismini qoyib beradi, bu funksiyamiz orqali arr ishlaitb bolmaydi, chunki u butun sonlar


In [9]:
arr1 = np.random.randn(6) # 6ta elementdan iborat taxminiy 
arr1

array([ 1.33977025, -1.68115741, -0.70859973, -1.3524437 ,  1.59124459,
        0.28091387])

In [10]:
qoldiq, butun = np.modf(arr1)

In [11]:
print(butun)
print(qoldiq)

[ 1. -1. -0. -1.  1.  0.]
[ 0.33977025 -0.68115741 -0.70859973 -0.3524437   0.59124459  0.28091387]


sign funksiyasi massiv elementlarini qiymati manfiy bo'lsa -1 va aksincha musbat bolsa 1ni qaytaradi

In [12]:
np.sign(arr1)

array([ 1., -1., -1., -1.,  1.,  1.])

isnan massivning elementlarida NaN malumoti bolsa True qaytaradi va aksincha False qaytaradi

In [13]:
np.isnan(arr1)

array([False, False, False, False, False, False])

Unary funksiyalar:

abs, fabs - Absolut qiymatni qaytaradi <br>
log, log2, log10, log1p - e asosga kora natural logarifm, 10 asosga kora, 2 asosga kora, log(1+x) ...<br>
ceil - Oziga teng yoki ozidan katta bolgan eng yaqin butun (int) sonni qaytaradi<br>
floor - Oziga teng yoki ozidan kichik bolgan eng yaqin butun (int) sonni qaytaradi<br>
rint - Butun sonni int korinishida yaxlitlaydi<br>
cos, cosh, sin, sinh, tan, tanh - trigonametrik funksiyalar<br>
arccos, arccosh, arcsin, arcsinh, arctan, arctanh - trigonametrik funksiyalar<br>



### Binary funksiyalar (ikta argument qabul qiluvchi funksiya)
add, multiply, maximum

add - ikkita massivning mos elementlarini qo'shadi


In [14]:
arr2 = np.random.randn(6)
arr3 = np.random.randn(6)
print(arr2)
print(arr3)

[ 0.147839    0.30421656 -0.30422028  0.93963529 -1.50064208 -0.35582791]
[ 0.02666856  0.87640206 -0.11275422  0.40634126 -2.02338963  0.37686562]


In [15]:
np.add(arr2, arr3) # arr1 ni arr2 ga elementlarini mos ravishda qo'shib beradi

array([ 0.17450756,  1.18061862, -0.4169745 ,  1.34597655, -3.5240317 ,
        0.02103771])

In [16]:
arr2 + arr3 # yuqoridagi qo'shish bilan bir xil usul

array([ 0.17450756,  1.18061862, -0.4169745 ,  1.34597655, -3.5240317 ,
        0.02103771])

multiply - ikta massivning mos elementlarini kopaytiradi

In [17]:
np.multiply(arr2, arr3) 

array([ 0.00394265,  0.26661602,  0.03430212,  0.38181259,  3.03638361,
       -0.13409931])

maximum - ikta massivning elementlarini taqqoslab ulardan kattasini qiymatin qaytaradi

In [18]:
np.maximum(arr2, arr3)

array([ 0.147839  ,  0.87640206, -0.11275422,  0.93963529, -1.50064208,
        0.37686562])

### binary funksiyalar

Har bir element (element-wise) uchun amallar bajaruvchi funksiyalar
<br>
subtract - birinchi massiv elementlarini ikkinchi massiv elementlariga mos ravishda ayiradi<br>
power - birinchi massiv elementlarini ikkinchi massiv elementlarda korsatilingan darajalar oshiradi<br>
max, fmax - ikkala array mos qiymatlarini solishtirib maksimumini qaytaradi, fmax esa NAN larni hisobga olmaydi<br>
min, fmin - ikkala array mos qiymatlarini solishtirib minumumini qaytaradi, fmin esa NAN larni hisobga olmaydi<br>
mod - massiv elementlarini bo'lib, bo'linmadan qoldigini (faqat butun qismini) qaytaradi<br>
copysign - ikkinchi argumetn ishorasini birinchi argumentga nusxalash vazifasini bajaradi<br>
greater, greater_equal, less, less_equal, equal, not_equal - mos elementlar aro taqqoslash amalini bajarib boolean arrayini qaytaradi<br>
logical_and, logical_or, logical_xor - mos elementlar aro mantiqiy amallarni bajaradi (&, |, ^)