<a href="https://colab.research.google.com/github/jfcoderx/Data-Sciense/blob/main/10_Matemetik_va_Statistik_amallar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Massivga yo'naltirilgan dasturlash

### Matematik va Statistik amallarni qo'llash



### Asosiy statistik metodlar

**sum** - Arraydagi barcha elementlar yigindisi <br>
**mean** - O'rtacha arifmetik qiymat <br>
**std, var** - Standart og'ish va variatsiya <br>
**min, max** - Minimum va Maksimum <br>
**cumsum** - Yig'ilib boradigan yigindi (cumulative) <br>
**cumprod** - Yig'ilib boradigan ko'paytma <br>

In [1]:
import numpy as np

In [3]:
# data
arr = np.random.randn(5, 4) # (5, 4) o'lchamli massiv
arr

array([[ 1.54887189, -1.02957235, -0.3761213 , -0.14280922],
       [ 0.61144131,  1.02822001, -0.23600979,  1.08151442],
       [ 1.59284688,  1.64569734,  1.36365157, -0.16787738],
       [-0.35715572,  2.14965551, -1.47605998, -0.58187923],
       [ 0.49088853, -0.33212645, -0.35700349,  0.90164053]])

SUM metodi barcha elementlarning yigindisini hisoblaydi

In [7]:
arr.sum()

7.3578130680942895

In [8]:
np.sum(arr)

7.3578130680942895

vertikal oqimiz nolchi oq edi axis0 <br>
gorizontal oqimiz birinchi oq edi axis1 <br>

Qatorlarni yigindisini topish kelganda demak axes1 oqidan foydalanamiz

In [11]:
arr.sum(axis=1) # gorizontal oqlardagi elementlar yigindisi (qatorlar yigindi)

array([ 3.69019611e-04,  2.48516594e+00,  4.43431840e+00, -2.65439421e-01,
        7.03399128e-01])

Ustunlar yigindisini topish kelganda demak axes0 oqidan foydalanamiz

In [12]:
arr.sum(axis=0) # vertikal oqlardagi elementlar yigindisi (ustunlar yigindi)

array([ 3.88689288,  3.46187406, -1.081543  ,  1.09058912])

MEAN metodi <br>
ortacha arifmetik qiymat, barcha elementlarining yigindisini osha elementlar soniga bolinmasi tushuniladi

In [13]:
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [14]:
# oddiy arifmetika bilan barajaramiz
np.sum(data) / len(data)

2.0

In [17]:
# numpy kutubxonasi orqali
data.mean()

2.0

In [18]:
np.mean(data)

2.0

In [19]:
arr

array([[ 1.54887189, -1.02957235, -0.3761213 , -0.14280922],
       [ 0.61144131,  1.02822001, -0.23600979,  1.08151442],
       [ 1.59284688,  1.64569734,  1.36365157, -0.16787738],
       [-0.35715572,  2.14965551, -1.47605998, -0.58187923],
       [ 0.49088853, -0.33212645, -0.35700349,  0.90164053]])

In [21]:
np.mean(arr) # arr massimizdagi elementlarimizning ortacha qiymati ekan

0.3678906534047145

In [22]:
arr.mean(axis=1) # gorizontal oqlardagi elementlarning ortacha qiymati

array([ 9.22549029e-05,  6.21291485e-01,  1.10857960e+00, -6.63598552e-02,
        1.75849782e-01])

In [24]:
np.mean(arr, axis=1) # gorizontal oqlardagi elementlarning ortacha qiymati (qator boyicha ort qiymat)

array([ 9.22549029e-05,  6.21291485e-01,  1.10857960e+00, -6.63598552e-02,
        1.75849782e-01])

In [23]:
arr.mean(axis=0) # vertikal oqlardagi elementlarning ortacha qiymati

array([ 0.77737858,  0.69237481, -0.2163086 ,  0.21811782])

In [25]:
np.mean(arr, axis=0) # vertikal oqlardagi elementlarning ortacha qiymati (ustun boyicha ort qiymat)

array([ 0.77737858,  0.69237481, -0.2163086 ,  0.21811782])

CUMSUM metodi <br>
Cumulative Sum <br>
Barcha yigindilarni yigib boradigan metod

In [26]:
data

array([0, 1, 2, 3, 4])

Bunga CUMSUM metodini qollasak:<br>
1-elementimiz 0, undan oldin element yoq shu uchun uning shu nuqtagacha yigindisi ozi bilan 0,<br>
2-elementimiz 1, undan oldin element 0, shu uchun uning shu nuqtagacha yigindisi ozi bilan 1,<br>
3-elementimiz 2, undan oldin element 0, 1, shu uchun uning shu nuqtagacha yigindisi ozi bilan 3,<br>
4-elementimiz 3, undan oldin element 0, 1, 2, shu uchun uning shu nuqtagacha yigindisi ozi bilan 6,<br>
4-elementimiz 4, undan oldin element 0, 1, 2, 3, shu uchun uning shu nuqtagacha yigindisi ozi bilan 10<br>

In [27]:
data.cumsum()

array([ 0,  1,  3,  6, 10])

In [28]:
np.cumsum(data)

array([ 0,  1,  3,  6, 10])