<a href="https://colab.research.google.com/github/jfcoderx/Data-Sciense/blob/main/11_Tartiblash_Sotring.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Massivga yonaltirilgan dasturlash

### Sorting (tartiblash)

In [1]:
import numpy as np

In [3]:
# data
arr = np.random.rand(4) # 4ta taxminiy elementlardan tashkil topgan massiv, rand (0 va 1) oraligidagi taxminiy elementlarni yaratib beradi
arr

array([0.87954372, 0.83773378, 0.12896767, 0.74584831])

SORT funksiyasi

In [6]:
# asl arr ozgartimagan holda tartiblaymiz
sorted_arr = np.sort(arr) # arr massivimizning tartiblangan versiyasi, defaul qiymatda osish holatida oladi
sorted_arr

array([0.12896767, 0.74584831, 0.83773378, 0.87954372])

In [8]:
# togridan togri asl arr ustida tartiblashni bajaramiz
arr.sort()
arr

array([0.12896767, 0.74584831, 0.83773378, 0.87954372])

In [10]:
# teskari tartiblash, numpyda teskari tartiblash uchun alohida funksiya yoq
# lekin buni yoli bor

rev_arr = -np.sort(-arr) # teskari tartibdagi arr
rev_arr

array([0.87954372, 0.83773378, 0.74584831, 0.12896767])

### Kop olchamli massivlarda tartiblash

In [11]:
# 2D array
arr2d = np.random.randn(2, 4) # (2, 4) random massiv
arr2d

array([[-0.04976463,  2.07370205,  1.07166967, -1.40093821],
       [-0.54037054,  0.81433049, -1.29298703,  0.8189118 ]])

In [13]:
# axis = 0 --> Qator oqi
row_srt = np.sort(arr2d, axis=0) # arr2d ning bir QATOR boyicha tartiblangan ko'rinishi
row_srt

array([[-0.54037054,  0.81433049, -1.29298703, -1.40093821],
       [-0.04976463,  2.07370205,  1.07166967,  0.8189118 ]])

In [14]:
# axis = 1 --> Ustun oqi
col_srt = np.sort(arr2d, axis=1) # arr2d ning bir QATOR boyicha tartiblangan ko'rinishi
col_srt

array([[-1.40093821, -0.04976463,  1.07166967,  2.07370205],
       [-1.29298703, -0.54037054,  0.81433049,  0.8189118 ]])