<a href="https://colab.research.google.com/github/jfcoderx/Data-Sciense/blob/main/14_Chiziqli_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Malumotlar tahlili. NumPy
### Chiziqli algebra
Matritsalar va vektorlar ustida sodda amallarni koramiz

In [1]:
import numpy as np

In [4]:
# matritsa, 2 olchovli massiv
x = np.arange(1, 7).reshape(2, 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
y = np.arange(7, 13).reshape(2, 3)
y

array([[ 7,  8,  9],
       [10, 11, 12]])

In [13]:
x + y

array([[ 8, 10, 12],
       [14, 16, 18]])

In [15]:
y - x

array([[6, 6, 6],
       [6, 6, 6]])

skalar kopaytirish<br>
arrayning har bir elementlarini bir songa kopaytirish

In [16]:
x * 5

array([[ 5, 10, 15],
       [20, 25, 30]])

Arraylarni kopaytirishni oziga yarasha qoidalari bor: <br>
1-matritsalarni ustunlari soni 2-matritsaning qatorlar soniga teng bolishi kerak<br>
(2, 3) matritsamizni, (3, 2) matritsaga kopaytirishimiz mumkin<br>
<br>
1 2 3 <br>
4 5 6 <br>
<br>
10 11 <br>
20 21 <br>
30 31 <br>
<br>
1x10 + 2x20 + 3x30 --- 1x11 + 2x21 + 3x31 <br>
4x10 + 5x20 + 6x30 --- 4x11 + 5x21 + 6x31 <br>
<br>
140 146 <br>
320 335

In [17]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
y = np.arange(7, 13).reshape(3, 2)
y

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

DOT metodigan foydananmiz bu uchun

In [21]:
x.dot(y) # x*y, x ni y ga kopaytiryapmi

array([[ 58,  64],
       [139, 154]])

In [22]:
np.dot(x, y)

array([[ 58,  64],
       [139, 154]])

In [23]:
y.dot(x) # y*x, y ni x ga kopaytiryapmiz

array([[ 39,  54,  69],
       [ 49,  68,  87],
       [ 59,  82, 105]])

In [24]:
np.dot(y, x) # (y * x)

array([[ 39,  54,  69],
       [ 49,  68,  87],
       [ 59,  82, 105]])