<a href="https://colab.research.google.com/github/jfcoderx/Data-Sciense/blob/main/3-Indexing-Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Indeks va Kesib olish asoslari
Massiv malumotlari turgan joylar indekslar deyishimiz mumkin, pythondagi list malumotlari indekslari malumotlarning joylarini ifodalani kabi <br>

Malumotlar elementlarining indeksi NOLdan boshlanadi
0, 1, 2 ...
oxirgi elementdan boshiga kelganda esa oxirgi element indeksi 
-1, -2, -3 ... ko'rinishida bo'ladi


In [1]:
import numpy as np

In [5]:
arr_1d = np.arange(10, 100, 10) # 100 kirmaydi
arr_1d

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

massivni yaratib oldik, endi indeks orqali uni elemtlarini topa olamiz, <br>
bir o'lchamli massivlarning indeksni kiritish python list bilan deyarli bir xil

In [6]:
arr_1d[0] # nol indeksdagi element

10

In [7]:
arr_1d[-1] # oxirgi indeksdagi element

90

bir o'lchamli massivlarni kesib olish ham python list elementlarini kesib olish bilan bir xil


In [9]:
arr_1d[2:5] # indeks 2dagi elementdan 5indeks elementigacha, 5 kirmaydi

array([30, 40, 50])

### Biroz xavfli
NumPy kutubxonasidagi massivning kesib olingan qisga o'zgartirish kiritilsa, asosiy massivga tasir qiladi 

In [10]:
arr_1d

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [11]:
sliced_arr = arr_1d[2:5]
sliced_arr

array([30, 40, 50])