<a href="https://colab.research.google.com/github/jfcoderx/Data-Sciense/blob/main/9_Arifmetik_amallar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Massivga yo'naltirilgan dasturlash

### Arifmetik amallar

Qo'shish, Ayirish, Ko'paytirish, Bo'lish

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(6).reshape(2, 3)  # 0dan 6gacha, 6 kirmaydi, (2, 3) shaklli
arr2 = np.arange(6, 12).reshape(2, 3) # 6dan 12gacha, 12 kirmaydi, (2, 3) shaklli

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [6]:
# Ko'paytirish
arr1 * arr2 # arr1 elementlarini arr2 elementlariga mos ravishda kopaytirib beradi

array([[ 0,  7, 16],
       [27, 40, 55]])

In [7]:
# Bo'lish
arr1 / arr2 # arr1 elementlarini arr2 elementlariga mos ravishda bolib beradi

array([[0.        , 0.14285714, 0.25      ],
       [0.33333333, 0.4       , 0.45454545]])

In [8]:
# Bo'lish
arr2 / arr1 # arr2 elementlarini arr1 elementlariga mos ravishda bolib beradi

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([[inf, 7. , 4. ],
       [3. , 2.5, 2.2]])

In [9]:
# Qo'shish
arr1 + arr2 #  arr1 elementlarini arr2 elementlariga mos ravishda qoshib beradi

array([[ 6,  8, 10],
       [12, 14, 16]])

In [10]:
# Ayirish
arr1 - arr2 #  arr1 elementlarini arr2 elementlariga mos ravishda ayirib beradi

array([[-6, -6, -6],
       [-6, -6, -6]])

In [11]:
# Ayirish
arr2 - arr1 #  arr2 elementlarini arr1 elementlariga mos ravishda ayirib beradi

array([[6, 6, 6],
       [6, 6, 6]])

In [12]:
# kvadratga oshirish (square)
arr1 ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [14]:
# kubga oshirish
arr2 ** 3

array([[ 216,  343,  512],
       [ 729, 1000, 1331]])

In [15]:
# kvadrat ildizdan chiqarish (sqrt)
arr1 ** 0.5

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798]])

Pythondagi arifmetik amallar bilan deyarli bir xil, ammo ustunligi bir vaqtning o'zida bir nechta elementlar ustida amallarni bajarish mumkin ekan