<a href="https://colab.research.google.com/github/jfcoderx/Data-Sciense/blob/main/Data_type.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Malumot Turlari
Pythondagi malumot turlari kabi NumPy kutubxonasida ham malumotlar bor

**bool** - Boolean (True / False) byte ko`rinishida saqlanadi <br>
intc - C dasturlash tilining int malumot turi bilan bir xil (int32 yoki int64) <br>
**int8** - byte (-128 dan 127 gacha) <br>
**int16** - Integer (-32768 dan 32767 gacha) <br>
**int32** - Integer (-2147483648 dan 2147483647 gacha) <br>
**int64** - Integer (-9223372036854775808 dan 9223372036854775807 gacha) <br>
**uint8** -  Unsigned (musbat) Integer(0 dan 255 gacha) <br>
**uint16** - Unsigned (musbat) Integer(0 dan 65535 gacha) <br>
**uint32** - Unsigned (musbat) Integer(0 dan 4294967295 gacha) <br>
**uint64** - Unsigned (musbat) Integer(0 dan 18446744073709551615 gacha) <br>
**float16** - Yarim aniqlikdagi float: sign (ishora) bit, 5bits exponent, 10bits mantissa <br>
**float32** - Bir aniqlikdagi float: sign (ishora) bit, 8bits exponent, 23bits mantissa <br>
**float64** - Ikki aniqlikdagi float: sign (ishora) bit, 11bits exponent, 52bits mantissa <br>
**complex64** - Kompleks raqam, ikkita 32-bitlik floatlar yordamida tashkil topadi <br>
**complex128** - Kompleks raqam, ikkita 64-bitlik floatlar yordamida tashkil topadi <br>
**string** - ASCII string turi (bitta harakterga 1 byte) <br>

Numpy kutubxonasining malumot turlarin bunday bitlarga bo'lishini uning ustunligi sanaladi, bunday ajratilishining sababi, biz NumPy kutubxonasida malumotlar yaratganimizda yoki malumotlar ustida amallar bajarganimizda, shu malumotlarimizni xotiradan egallaydigan joylarini ustidan nazorat ornata olamiz <br>
Tasavvur qiling sizning 1mln malumotingiz bor, har bir elementi butun sonlar, va ular (-32768 dan 32767) oraligida, bu holda siz int16 malumot turini belgilab ketadigan bo'lsangiz, siz xotiradan yaxshigina joyni tejab qolgan bo'lasiz
<br>
Siz NumPyda malumot yaratib uning aniq turini korsatmasangiz u int64 malumot turini defaul malumot turi sifatida qabul qiladi, bu esa xotirada koproq joy olib kelishi mumkin, agar sizning malumotingiz juda kop bolsa malumot turini aniq korsatish kerak, aksariyat hollarda NumPy ni oziga topshirilsa ham boladi

In [1]:
import numpy as np

Massivlar yaratishda ma'lumot turini aniq kiritish, ma'lumot turlarini aniqlash, bir turdan ikkinchi turga ma'lumot turini o'girish <br>
array() funksiyasi ichida DTYPE degan parametri ham qabul qiladi, aynan shunga malumot turini korsatib ketishimiz mumkin

In [3]:
arr_float64 = np.array([1, 2, 3], dtype=np.float64) # float64 malumot turiga ega massiv, arrayni chop qilamiz, integer list kiritsak ham float massiv hosil qiladi
arr_float64

array([1., 2., 3.])

In [4]:
arr_int32 = np.array([1, 2, 3], dtype=np.int32) # int32 malumot turiga ega massiv
arr_int32

array([1, 2, 3], dtype=int32)

.DTYPE orqali istalgan malumot turimizni tekshira olamiz

In [5]:
arr_float64.dtype

dtype('float64')

Bir turdagi malumot turidan boshqasiga o'tkazish

In [7]:
arr_int = np.array([1, 2, 3, 4]) # dtype korsatilmasa va int malumotlar kiritlgan bolsa avtomat int64 oladi
arr_int.dtype

dtype('int64')

int64 malumot turimizni float64 ga o'girib ko'raylik <br>
astype metodi orqali

In [8]:
arr_float = arr_int.astype(np.float64)
arr_float

array([1., 2., 3., 4.])

In [9]:
arr_float32 = arr_int.astype(np.float32)
arr_float32

array([1., 2., 3., 4.], dtype=float32)

### ogohlik
float malumot turidan integer malumot turiga o'tayoganimizda biror yuqotish bo'lishi mumkin

In [12]:
data_float = np.array([1.2, 3.9, 0.4, 7]) # defaul float64
data_float

array([1.2, 3.9, 0.4, 7. ])

In [13]:
data_int = data_float.astype(np.int64)
data_int

array([1, 3, 0, 7])

Demak floatdan integer ga otayogan floatning faqat butun qismini oladi, kasr qismini esa tashlab yuboradi