<a href="https://colab.research.google.com/github/jfcoderx/Data-Sciense/blob/main/_3_Indexing%26Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Indeks va Kesib olish asoslari
Massiv malumotlari turgan joylar indekslar deyishimiz mumkin, pythondagi list malumotlari indekslari malumotlarning joylarini ifodalani kabi <br>

Malumotlar elementlarining indeksi NOLdan boshlanadi
0, 1, 2 ...
oxirgi elementdan boshiga kelganda esa oxirgi element indeksi 
-1, -2, -3 ... ko'rinishida bo'ladi


In [1]:
import numpy as np

In [5]:
arr_1d = np.arange(10, 100, 10) # 100 kirmaydi
arr_1d

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

massivni yaratib oldik, endi indeks orqali uni elemtlarini topa olamiz, <br>
bir o'lchamli massivlarning indeksni kiritish python list bilan deyarli bir xil

In [6]:
arr_1d[0] # nol indeksdagi element

10

In [7]:
arr_1d[-1] # oxirgi indeksdagi element

90

bir o'lchamli massivlarni kesib olish ham python list elementlarini kesib olish bilan bir xil


In [9]:
arr_1d[2:5] # indeks 2dagi elementdan 5indeks elementigacha, 5 kirmaydi

array([30, 40, 50])

### Biroz xavfli
NumPy kutubxonasidagi massivning kesib olingan qisga o'zgartirish kiritilsa, asosiy massivga tasir qiladi 

In [10]:
arr_1d

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [11]:
sliced_arr = arr_1d[2:5]
sliced_arr

array([30, 40, 50])

endi kesib olingan massivimiz qismini hammasini NOLGA tenglab qo'yaylik

In [12]:
sliced_arr[:] = 0
sliced_arr

array([0, 0, 0])

In [13]:
arr_1d

array([10, 20,  0,  0,  0, 60, 70, 80, 90])

ko'rinib turibdiki, asosiy massivimizning elementlari ham ozgardi
asosiy massivimiz ozgarmasiligi uchun copy() dan foydalanamiz

In [19]:
arr1 = np.arange(10, 100, 10)
sliced_arr_copy = arr1[2:5].copy()
sliced_arr_copy2 = arr1[2:5][:]

In [20]:
print(arr1)
print(sliced_arr_copy)
print(sliced_arr_copy2)

[10 20 30 40 50 60 70 80 90]
[30 40 50]
[30 40 50]


In [21]:
sliced_arr_copy[:] = 0
sliced_arr_copy2[:] = 1

print(arr1)
print(sliced_arr_copy)
print(sliced_arr_copy2)

[10 20  1  1  1 60 70 80 90]
[0 0 0]
[1 1 1]


## 2-o'lchamli massivlar indek va kesib olish asoslari

In [22]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # (3, 3) o'lchamli massiv
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Demak bunda <br>
1, 4, 7 bo'ylab yo'nalgan o'q qatorlarni ifodalaydi <br>
7, 8, 9 bo'ylab yo'nalgan o'q ustunlarni ifodalaydi <br><br>

(0,0)  (0,1)  (0,2) <br>
(1,0)  (1,1)  (1,2) <br>
(2,0)  (2,1)  (2,2) <br>

yuqoridagi massivimizdan 6 soni ajratib olishimiz uchun

In [23]:
arr2d[1, 2] # 1-indeksli qator, 2-indeksli ustun

6

2-o'lchamli massivlarni bir nechta elementini kesib olish

In [24]:
sl_arr2d = arr2d[2, 1:3] # yani 2-qator, 1-ustundan 3-ustungacha, 3-ustun kirmaydi
sl_arr2d

array([8, 9])

In [25]:
sl_arr2d = arr2d[2, 1:] # yani 2-qator, 1-ustundan oxirgi ustungacha 
sl_arr2d

array([8, 9])

### Kesib olishga bazi yordamlar
arr = <br>
[ 1, 2, 3 ]<br>
[ 4, 5, 6 ]<br>
[ 7, 8, 9 ]<br><br>

[ -, 2, 3 ]<br>
[ -, 5, 6 ]<br>
[ -, -, - ]<br>
buni kesib olish <br> arr [ :2, 1: ] - yoki - arr [ 0:2, 1:3 ] -- (2,2)

<br>
[ -, -, - ]<br>
[ -, -, - ]<br>
[ 7, 8, 9 ]<br>
buni kesib olish <br> arr [ 2 ] - yoki - arr [ 2, : ] - yoki - arr [ 2, 0:3 ] - yoki - arr [ -1 ] -- (1,3) <br>

<br>
[ 1, 2, - ]<br>
[ 4, 5, - ]<br>
[ 7, 8, - ]<br>
buni kesib olish <br> arr [ :, :2 ]  -- (3,2) <br>

<br>
[ -, -, - ]<br>
[ 4, 5, - ]<br>
[ -, -, - ]<br>
buni kesib olish <br> arr [ 1, :2 ]  -- (1, 2)


## 3 o'lchamli massivlarda indeks va kesib olish asoslari

x, y, z o'qlari kabi tasavvur qilishimiz mumkin <br>
shape(3, 3, 3)

In [27]:
data = [
            [
                [11, 12, 13], 
                [14, 15, 16], 
                [17, 18, 19]
            ],
            [
                [21, 22, 23],
                [24, 25, 26],
                [27, 28, 29]
            ],
            [
                [31, 32, 33],
                [34, 35, 36],
                [37, 38, 39]
            ]
        ]

arr3d = np.array(data)
arr3d

array([[[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[31, 32, 33],
        [34, 35, 36],
        [37, 38, 39]]])

buni kesib olishni oson qilishiimiz uchun uni kichik 2 olchamli massivlar sifatida qarab olsak boladi, bu yerda 3 ta 2 olchamli massiv bor deb hisoblasak boladi <br>

demak birinchi ikki o'lchamli massivimiz indeksimiz 0,<br>
ikkinchi ikki o'lchamli massivimiz indeksimiz 1,<br>
birinchi ikki o'lchamli massivimiz indeksimiz 2,<br>

va qolgani ikki o'lchamli massivimizni kesishini aynan ozi<br>

In [28]:
arr3d[0] # birinchi ikki o'lchamli massivimiz


array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

shuni 16 elementini olib chiqarsak

In [29]:
arr3d[0][1, 2]

16

In [30]:
arr3d[1] # ikkinchi ikki o'lchamli massivimiz

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [31]:
arr3d[2] # uchinchi ikki o'lchamli massivimiz

array([[31, 32, 33],
       [34, 35, 36],
       [37, 38, 39]])

In [32]:
arr3d[2][:2, :2] # 31, 32, 34, 35 shularni ajratib olish

array([[31, 32],
       [34, 35]])