<a href="https://colab.research.google.com/github/jfcoderx/Data-Sciense/blob/main/TAKRORLASH_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## TAKRORLASH NUMPY

In [2]:
import numpy as np

In [3]:
# LIST vs ARRAY
list_yuzming = list(range(100000)) # 0 - 99999  --> Normal
arr_yuzming = np.array(range(100000)) # 0 - 99999  --> Vektorlashgan

In [4]:
# har bir hisoblashlarga ketgan vaqtlar
%time for _ in range(10): [x*2 for x in list_yuzming] # Normal
%time for _ in range(10): arr_yuzming * 2 # Vektorlashgan

CPU times: user 69.6 ms, sys: 15.8 ms, total: 85.4 ms
Wall time: 105 ms
CPU times: user 1.82 ms, sys: 0 ns, total: 1.82 ms
Wall time: 4.21 ms


In [5]:
# Bir biridan necha martaga ortiqligi
95.2 / 1.63

58.40490797546013

In [6]:
# 1D MASSIV
arr1d = np.array([1, 2, 3])
arr1d

array([1, 2, 3])

In [7]:
# 2D MASSIV
arr2d = np.array([
                  [1, 2, 3], 
                  [4, 5, 6],
                  [7, 8, 9]
                 ]) 
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# 3D MASSIV
arr3d = np.array([
                    [
                        [11, 12, 13],
                        [14, 15, 16],
                        [17, 18, 19]
                    ],
                    [
                        [21, 22, 23], 
                        [24, 25, 26],
                        [27, 28, 29]
                    ],
                    [
                        [31, 32, 33],
                        [34, 35, 36],
                        [37, 38, 39]
                    ]
                  ])
arr3d 

array([[[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[31, 32, 33],
        [34, 35, 36],
        [37, 38, 39]]])

In [9]:
# NDIM - massiv o'lchamini korsatadi
print(arr1d.ndim)
print(arr2d.ndim)
print(arr3d.ndim)

# TYPE - massiv tipini korsatadi
print(type(arr1d))
print(type(arr2d))
print(type(arr3d))

1
2
3
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [10]:
# SHAPE - qator va ustunlar soni korsatadi
print(arr1d.shape)
print(arr2d.shape)
print(arr3d.shape)

(3,)
(3, 3)
(3, 3, 3)


In [11]:
# SIZE - massiv elementlar soni korsatadi
# shapelar soni bir biriga kopaytirsa massiv elementlar soni chiqarkan
print(arr1d.size)
print(arr2d.size)
print(arr3d.size)

3
9
27


In [12]:
# ZEROS, ONES, EMPTY, FULL --> 1D

arr_empty1 = np.empty(4)
arr_full1 = np.full((4), 44)
arr_zeros1 = np.zeros(4)
arr_ones1 = np.ones(4)

print(arr_empty1)
print(arr_full1)
print(arr_zeros1)
print(arr_ones1)

[5.e-324 5.e-324 5.e-324 0.e+000]
[44 44 44 44]
[0. 0. 0. 0.]
[1. 1. 1. 1.]


In [13]:
# ZEROS, ONES, EMPTY, FULL --> 2D (1, 4)

arr_empty2 = np.empty((1, 4))
arr_full2 = np.full((1, 4), 44)
arr_zeros2 = np.zeros((1, 4))
arr_ones2 = np.ones((1, 4))

print(arr_empty2)
print()
print(arr_full2)
print()
print(arr_zeros2)
print()
print(arr_ones2)

[[1. 1. 1. 1.]]

[[44 44 44 44]]

[[0. 0. 0. 0.]]

[[1. 1. 1. 1.]]


In [14]:
# ZEROS, ONES, EMPTY, FULL --> 2D (4, 1)

arr_empty2 = np.empty((4, 1))
arr_full2 = np.full((4, 1), 44)
arr_zeros2 = np.zeros((4, 1))
arr_ones2 = np.ones((4, 1))

print(arr_empty2)
print()
print(arr_full2)
print()
print(arr_zeros2)
print()
print(arr_ones2)

[[1.]
 [1.]
 [1.]
 [1.]]

[[44]
 [44]
 [44]
 [44]]

[[0.]
 [0.]
 [0.]
 [0.]]

[[1.]
 [1.]
 [1.]
 [1.]]


In [15]:
# ZEROS, ONES, EMPTY, FULL --> 3D (3, 3, 3)

arr_empty3 = np.empty((3, 3, 3))
arr_full3 = np.full((3, 3, 3), 444)
arr_zeros3 = np.zeros((3, 3, 3))
arr_ones3 = np.ones((3, 3, 3))

print(arr_empty3)
print()
print(arr_full3)
print()
print(arr_zeros3)
print()
print(arr_ones3)

[[[2.62209571e-316 8.84377506e-322 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 1.16095484e-028]
  [1.64781299e+098 4.80282051e+006 6.69435463e+151]]

 [[1.39806873e-152 8.15327665e+241 1.39837037e-076]
  [7.13227254e-154 4.85787477e-033 2.18953547e+068]
  [2.13424455e+161 7.05131940e+199 5.28595592e-085]]

 [[2.55286675e+161 1.39804456e-076 6.96818306e-077]
  [4.85787506e-033 1.43456201e+180 1.41476254e+195]
  [1.46899930e+179 9.08367237e+223 1.16466228e-028]]]

[[[444 444 444]
  [444 444 444]
  [444 444 444]]

 [[444 444 444]
  [444 444 444]
  [444 444 444]]

 [[444 444 444]
  [444 444 444]
  [444 444 444]]]

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [16]:
arr1d

array([1, 2, 3])

In [17]:
# ZEROS_LIKE, ONES_LIKE, EMPTY_LIKE, FULL_LIKE --> 1D

arr_empty_like1 = np.empty_like(arr1d)
arr_full_like1 = np.full_like(arr1d, 44)
arr_zeros_like1 = np.zeros_like(arr1d)
arr_ones_like1 = np.ones_like(arr1d)

print(arr_empty_like1)
print(arr_full_like1)
print(arr_zeros_like1)
print(arr_ones_like1)

[1 1 1]
[44 44 44]
[0 0 0]
[1 1 1]


In [18]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
# ZEROS_LIKE, ONES_LIKE, EMPTY_LIKE, FULL_LIKE --> 2D

arr_empty_like2 = np.empty_like(arr2d)
arr_full_like2 = np.full_like(arr2d, 44)
arr_zeros_like2 = np.zeros_like(arr2d)
arr_ones_like2 = np.ones_like(arr2d)

print(arr_empty_like2)
print()
print(arr_full_like2)
print()
print(arr_zeros_like2)
print()
print(arr_ones_like2)

[[           53148432                  36                   0]
 [                  0                   0 3761458305658073656]
 [3977854056740827693 3257564015184667960 7090462639664541798]]

[[44 44 44]
 [44 44 44]
 [44 44 44]]

[[0 0 0]
 [0 0 0]
 [0 0 0]]

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [20]:
arr3d

array([[[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[31, 32, 33],
        [34, 35, 36],
        [37, 38, 39]]])

In [21]:
# ZEROS_LIKE, ONES_LIKE, EMPTY_LIKE, FULL_LIKE --> 3D

arr_empty_like3 = np.empty_like(arr3d)
arr_full_like3 = np.full_like(arr3d, 444)
arr_zeros_like3 = np.zeros_like(arr3d)
arr_ones_like3 = np.ones_like(arr3d)

print(arr_empty_like3)
print()
print(arr_full_like3)
print()
print(arr_zeros_like3)
print()
print(arr_ones_like3)

[[[4607182418800017408 4607182418800017408 4607182418800017408]
  [4607182418800017408 4607182418800017408 4607182418800017408]
  [4607182418800017408 4607182418800017408 4607182418800017408]]

 [[4607182418800017408 4607182418800017408 4607182418800017408]
  [4607182418800017408 4607182418800017408 4607182418800017408]
  [4607182418800017408 4607182418800017408 4607182418800017408]]

 [[4607182418800017408 4607182418800017408 4607182418800017408]
  [4607182418800017408 4607182418800017408 4607182418800017408]
  [4607182418800017408 4607182418800017408 4607182418800017408]]]

[[[444 444 444]
  [444 444 444]
  [444 444 444]]

 [[444 444 444]
  [444 444 444]
  [444 444 444]]

 [[444 444 444]
  [444 444 444]
  [444 444 444]]]

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [22]:
# IDENTIFY - kvadrad matritsa, 2d massiv, asosiy diagonali - EYE ning xususiy holi
arr_identify = np.identity(4)
arr_identify

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
# EYE - istalgan diagonal
arr_eye = np.eye(4, None, 1)
arr_eye

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [24]:
arr1d

array([1, 2, 3])

In [25]:
# RESHAPE 1D --> 2D
arr1d.reshape(3, 1)

array([[1],
       [2],
       [3]])

In [26]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
# RESHAPE 2D --> 3D
arr2d.reshape(1, 3, 3)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [28]:
# RESHAPE 2D --> 3D
arr2d.reshape(3, 1, 3)

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [29]:
# RESHAPE 2D --> 3D
arr2d.reshape(3, 3, 1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [30]:
arr3d

array([[[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[31, 32, 33],
        [34, 35, 36],
        [37, 38, 39]]])

In [31]:
# RESHAPE 3D --> 2D
arr3d.reshape(9, 3)

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [31, 32, 33],
       [34, 35, 36],
       [37, 38, 39]])

In [32]:
# RESHAPE 3D --> 2D
arr3d.reshape(3, 9)

array([[11, 12, 13, 14, 15, 16, 17, 18, 19],
       [21, 22, 23, 24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [33]:
# RESHAPE 3D --> 2D
arr3d.reshape(1, 27)

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [34]:
# RESHAPE 3D --> 1D
arr3d.reshape(27, )

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [35]:
# RESHAPE 3D --> 1D
arr3d.reshape(27)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [36]:
# 3D array
arr = np.array([[[1]]])
arr

array([[[1]]])

In [37]:
# DTYPE - malumot turini aniqlash
print(arr1d.dtype)
print(arr2d.dtype)
print(arr3d.dtype)

int64
int64
int64


In [38]:
# DTYPE orqali massiv yaratish
arr1d = np.array([1.1, 2.2, 3.3], dtype=np.float32)
arr1d

array([1.1, 2.2, 3.3], dtype=float32)

In [39]:
# ASTYPE - malumot turini ozgartirish
arr2d = arr2d.astype(np.float32)
arr2d

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [40]:
# ASTYPE - malumot turini ozgartirish
arr3d = arr3d.astype(np.float32)
arr3d

array([[[11., 12., 13.],
        [14., 15., 16.],
        [17., 18., 19.]],

       [[21., 22., 23.],
        [24., 25., 26.],
        [27., 28., 29.]],

       [[31., 32., 33.],
        [34., 35., 36.],
        [37., 38., 39.]]], dtype=float32)

In [41]:
arr1d

array([1.1, 2.2, 3.3], dtype=float32)

In [42]:
# ASTYPE - float32 --> int64 - MALUMOT YUQOTILDI
arr1d = arr1d.astype(np.int64)
arr1d

array([1, 2, 3])

In [43]:
# 1D massiv 0-indeks
arr1d[0]

1

In [44]:
# 1D massiv 1-indeks
arr1d[-1]

3

In [45]:
# 1D massiv 0dan 2gacha
arr1d[0:2]

array([1, 2])

In [46]:
# 1D massiv - hammasi kesib olish
arr1d[:]

array([1, 2, 3])

In [47]:
# APPEND - oxiridan qoshadi, lekin asl arrayni ozgartirmaydi
# 1ta element qoshganimizda
arr1d = np.append(arr1d, 4)
arr1d

array([1, 2, 3, 4])

In [48]:
# APPEND - oxiridan qoshadi, lekin asl arrayni ozgartirmaydi
# bir nechta elementlar qoshganimizda
arr1d = np.append(arr1d, [5, 6, 7])
arr1d

array([1, 2, 3, 4, 5, 6, 7])

In [49]:
# CONCATENATE - 2 va undan ortiq elementlarni qoshish uchun, 
# encapsulate q k.k (arr, [elemets]), asl arrayni ozgartirmaydi
np.concatenate((arr1d, [111]))

array([  1,   2,   3,   4,   5,   6,   7, 111])

In [50]:
# CONCATENATE - 2 va undan ortiq elementlarni qoshish uchun, 
# encapsulate q k.k (arr, [elemets]), asl arrayni ozgartirmaydi
np.concatenate((arr1d, [100, 1000]))

array([   1,    2,    3,    4,    5,    6,    7,  100, 1000])

In [51]:
# INSERT - berilgan indeksdan berilgan elementlarni qoshadi, kiritadi

In [52]:
# boshiga qoshadi
np.insert(arr1d, 0, 555)

array([555,   1,   2,   3,   4,   5,   6,   7])

In [53]:
# oxirgi indeksga qoshadi
np.insert(arr1d, -1, 555)

array([  1,   2,   3,   4,   5,   6, 555,   7])

In [54]:
# oxiriga qoshadi
np.insert(arr1d, arr1d.size, 555)

array([  1,   2,   3,   4,   5,   6,   7, 555])

In [55]:
arr1d

array([1, 2, 3, 4, 5, 6, 7])

In [56]:
# array bir qismi kesib olindi
sl_arr = arr1d[2:5]
sl_arr

array([3, 4, 5])

In [57]:
# kesilgan qismi nolga tenglandi
sl_arr[:] = 0
sl_arr

array([0, 0, 0])

In [58]:
# asl array ham ozgardi
arr1d

array([1, 2, 0, 0, 0, 6, 7])

In [59]:
# COPY - arrayni kopy qilib beradi, asl array ozgarmayi shunda
sl_arr1 = arr1d[:4].copy()
sl_arr1

array([1, 2, 0, 0])

In [60]:
sl_arr1[:] = 11
sl_arr1

array([11, 11, 11, 11])

In [61]:
arr1d

array([1, 2, 0, 0, 0, 6, 7])

In [62]:
arr2d = arr2d.astype(np.int64)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
# arr[n] n-qator, 1D
# arr[n, m] n-qator, m-indek element, son
# arr[n, :m] n-qator, 0 dan - m gacha bolgan elementlar, 1D
# arr[:n, m] 0 dan n gacha qatorlardagi, m-indeks elementlar, 1D
# arr[:n, :m] 0 dan n gacha qator, 0 dan m gacha ustun li array, 2D

In [64]:
# 2D array, 0-indeks = 0-qator (1D-array)
arr2d[0]

array([1, 2, 3])

In [65]:
# 2D array, -1 indeks = oxirgi qator (1D-array)
arr2d[-1]

array([7, 8, 9])

In [66]:
# 0-qatorning 0-indeksidagi elementi
# yoki 0-qator va 0-ustun kesishgandagi element
arr2d[0, 0]

1

In [67]:
# (-1) qatorning (-1)-indeksidagi elementi
# yoki -1qator va -1ustundagi kesishgan element
arr2d[-1, -1]

9

In [68]:
# 1 qatorning , 0dan 2gacha turgan joyidagi elementlari
# yoki 1 qator, 0dan 2gacha ustunlarning kesishgan elementlari
arr2d[1, :2]

array([4, 5])

In [69]:
# 1 qatorning , 1dan oxirigacha turgan joyidagi elementlari
# yoki 1 qator, 1dan oxirigacha ustunlarning kesishgan elementlari
arr2d[1, 1:]

array([5, 6])

In [70]:
# hamma qatorning , 0- joyidagi elementlari
# yoki 0 ustunni ozidagi elementlar (1D massiv)
arr2d[:, 0]

array([1, 4, 7])

In [71]:
# hamma qatorning , 0- joyidagi elementlari
# yoki 0 ustunni ozidagi elementlar (2D massiv)
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [72]:
# hamma qatorning , 0 chi joyidagi elementlari
# yoki 0 ustunni ozidagi elementlar
arr2d[1:, :2]

array([[4, 5],
       [7, 8]])

In [73]:
arr2d[:, :]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
arr3d = arr3d.astype(np.int64)
arr3d

array([[[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[31, 32, 33],
        [34, 35, 36],
        [37, 38, 39]]])

In [75]:
# 0 - array --> 2D
arr3d[0]

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [76]:
# -1 - array --> 2D
arr3d[-1]

array([[31, 32, 33],
       [34, 35, 36],
       [37, 38, 39]])

In [77]:
# qolgani 2D indekslash bo'yicha ketadi
arr3d[0][0]

array([11, 12, 13])

In [78]:
arr3d[0][:, 0]

array([11, 14, 17])

In [79]:
arr3d[0][:, :1]

array([[11],
       [14],
       [17]])

In [80]:
arr3d[0][:2, :2]

array([[11, 12],
       [14, 15]])

In [81]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
# APPEND (2D) - 1ta qiymat berilsa, oxiridan qoshib 1D qaytararkan
np.append(arr2d, 222)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 222])

In [83]:
# APPEND (2D) - 3ta qiymat berilsa, oxiridan qoshib 1D qaytararkan
np.append(arr2d, [222, 222, 222])

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 222, 222, 222])

In [84]:
# APPEND (2D) - yangi qator qoshish, qoshiladigan malumot ham 2D bolishi kerak, 2D qaytaradi
np.append(arr2d, [[222, 222, 222]], axis=0)

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [222, 222, 222]])

In [85]:
# APPEND (2D) - yangi qator qoshish, qoshiladigan malumot ham 2D 
# va olchami bir xil bolishi kerak, 2D qaytaradi
np.append(arr2d, [[222, 222, 222], [222, 222, 222]], axis=0)

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [222, 222, 222],
       [222, 222, 222]])

In [86]:
# APPEND (2D) - yangi qator qoshish, qoshiladigan malumot ham 2D 
# va olchami bir xil bolishi kerak, 2D qaytaradi
np.append(arr2d, [[11],[14],[17]])


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 14, 17])

In [87]:
# CONCATENATE

"""
(__a: Any, /, axis: ... = ..., out: ... = ..., dtype: ... = ..., casting: ... = ...) -> Any
concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")

Join a sequence of arrays along an existing axis.

Parameters

a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
corresponding to axis (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
correct, matching that of what concatenate would have returned if no
out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
provided together with out.

casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
    Controls what kind of data casting may occur. Defaults to 'same_kind'.

Returns

res : ndarray
    The concatenated array.

See Also

ma.concatenate : Concatenate function that preserves input masks.
array_split : Split an array into multiple sub-arrays of equal or
              near-equal size.
split : Split array into a list of multiple sub-arrays of equal size.
hsplit : Split array into multiple sub-arrays horizontally (column wise).
vsplit : Split array into multiple sub-arrays vertically (row wise).
dsplit : Split array into multiple sub-arrays along the 3rd axis (depth).
stack : Stack a sequence of arrays along a new axis.
block : Assemble arrays from blocks.
hstack : Stack arrays in sequence horizontally (column wise).
vstack : Stack arrays in sequence vertically (row wise).
dstack : Stack arrays in sequence depth wise (along third dimension).
column_stack : Stack 1-D arrays as columns into a 2-D array.

Notes

When one or more of the arrays to be concatenated is a MaskedArray,
this function will return a MaskedArray object instead of an ndarray,
but the input masks are *not* preserved. In cases where a MaskedArray
is expected as input, use the ma.concatenate function from the masked
array module instead.

Examples

>>> a = np.array([[1, 2], [3, 4]])
>>> b = np.array([[5, 6]])
>>> np.concatenate((a, b), axis=0)
array([[1, 2],
       [3, 4],
       [5, 6]])
>>> np.concatenate((a, b.T), axis=1)
array([[1, 2, 5],
       [3, 4, 6]])
>>> np.concatenate((a, b), axis=None)
array([1, 2, 3, 4, 5, 6])
This function will not preserve masking of MaskedArray inputs.

>>> a = np.ma.arange(3)
>>> a[1] = np.ma.masked
>>> b = np.arange(2, 5)
>>> a
masked_array(data=[0, --, 2],
             mask=[False,  True, False],
       fill_value=999999)
>>> b
array([2, 3, 4])
>>> np.concatenate([a, b])
masked_array(data=[0, 1, 2, 2, 3, 4],
             mask=False,
       fill_value=999999)
>>> np.ma.concatenate([a, b])
masked_array(data=[0, --, 2, 2, 3, 4],
             mask=[False,  True, False, False, False, False],
       fill_value=999999)
"""

'\n(__a: Any, /, axis: ... = ..., out: ... = ..., dtype: ... = ..., casting: ... = ...) -> Any\nconcatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")\n\nJoin a sequence of arrays along an existing axis.\n\nParameters\n\na1, a2, ... : sequence of array_like\n    The arrays must have the same shape, except in the dimension\ncorresponding to axis (the first, by default).\naxis : int, optional\n    The axis along which the arrays will be joined.  If axis is None,\narrays are flattened before use.  Default is 0.\nout : ndarray, optional\n    If provided, the destination to place the result. The shape must be\ncorrect, matching that of what concatenate would have returned if no\nout argument were specified.\ndtype : str or dtype\n    If provided, the destination array will have this dtype. Cannot be\nprovided together with out.\n\ncasting : {\'no\', \'equiv\', \'safe\', \'same_kind\', \'unsafe\'}, optional\n    Controls what kind of data casting may occur. Defaults to

In [88]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
np.concatenate((arr2d, [[33, 44, 55]]), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [33, 44, 55]])

In [90]:
np.concatenate((arr2d, arr2d.T), axis=1)

array([[1, 2, 3, 1, 4, 7],
       [4, 5, 6, 2, 5, 8],
       [7, 8, 9, 3, 6, 9]])

In [91]:
# INSERT
"""
(arr: Any, obj: Any, values: Any, axis: ... = ...) -> Any
Insert values along the given axis before the given indices.

Parameters

arr : array_like
    Input array.
obj : int, slice or sequence of ints
    Object that defines the index or indices before which values is
inserted.

values : array_like
    Values to insert into arr. If the type of values is different
from that of arr, values is converted to the type of arr.
values should be shaped so that arr[...,obj,...] = values
is legal.
axis : int, optional
    Axis along which to insert values.  If axis is None then arr
is flattened first.

Returns

out : ndarray
    A copy of arr with values inserted.  Note that insert
    does not occur in-place: a new array is returned. If
axis is None, out is a flattened array.

See Also

append : Append elements at the end of an array.
concatenate : Join a sequence of arrays along an existing axis.
delete : Delete elements from an array.

Notes

Note that for higher dimensional inserts obj=0 behaves very different
from obj=[0] just like arr[:,0,:] = values is different from
arr[:,[0],:] = values.

Examples

>>> a = np.array([[1, 1], [2, 2], [3, 3]])
>>> a
array([[1, 1],
       [2, 2],
       [3, 3]])
>>> np.insert(a, 1, 5)
array([1, 5, 1, ..., 2, 3, 3])
>>> np.insert(a, 1, 5, axis=1)
array([[1, 5, 1],
       [2, 5, 2],
       [3, 5, 3]])
Difference between sequence and scalars:

>>> np.insert(a, [1], [[1],[2],[3]], axis=1)
array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])
>>> np.array_equal(np.insert(a, 1, [1, 2, 3], axis=1),
...                np.insert(a, [1], [[1],[2],[3]], axis=1))
True
>>> b = a.flatten()
>>> b
array([1, 1, 2, 2, 3, 3])
>>> np.insert(b, [2, 2], [5, 6])
array([1, 1, 5, ..., 2, 3, 3])
>>> np.insert(b, slice(2, 4), [5, 6])
array([1, 1, 5, ..., 2, 3, 3])
>>> np.insert(b, [2, 2], [7.13, False]) # type casting
array([1, 1, 7, ..., 2, 3, 3])
>>> x = np.arange(8).reshape(2, 4)
>>> idx = (1, 3)
>>> np.insert(x, idx, 999, axis=1)
array([[  0, 999,   1,   2, 999,   3],
       [  4, 999,   5,   6, 999,   7]])
"""

'\n(arr: Any, obj: Any, values: Any, axis: ... = ...) -> Any\nInsert values along the given axis before the given indices.\n\nParameters\n\narr : array_like\n    Input array.\nobj : int, slice or sequence of ints\n    Object that defines the index or indices before which values is\ninserted.\n\nvalues : array_like\n    Values to insert into arr. If the type of values is different\nfrom that of arr, values is converted to the type of arr.\nvalues should be shaped so that arr[...,obj,...] = values\nis legal.\naxis : int, optional\n    Axis along which to insert values.  If axis is None then arr\nis flattened first.\n\nReturns\n\nout : ndarray\n    A copy of arr with values inserted.  Note that insert\n    does not occur in-place: a new array is returned. If\naxis is None, out is a flattened array.\n\nSee Also\n\nappend : Append elements at the end of an array.\nconcatenate : Join a sequence of arrays along an existing axis.\ndelete : Delete elements from an array.\n\nNotes\n\nNote that f

---

In [92]:
# RANDOM.RADN
"""
() -> float
rand(d0, d1, ..., dn)

Random values in a given shape.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `random_sample`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    If no argument is given a single Python float is returned.

Returns
-------
out : ndarray, shape ``(d0, d1, ..., dn)``
    Random values.

See Also
--------
random

Examples
--------
>>> np.random.rand(3,2)
array([[ 0.14022471,  0.96360618],  #random
       [ 0.37601032,  0.25528411],  #random
       [ 0.49313049,  0.94909878]]) #random


(*args: int) -> ndarray[Any, dtype[float64]]
"""

'\n() -> float\nrand(d0, d1, ..., dn)\n\nRandom values in a given shape.\n\n.. note::\n    This is a convenience function for users porting code from Matlab,\n    and wraps `random_sample`. That function takes a\n    tuple to specify the size of the output, which is consistent with\n    other NumPy functions like `numpy.zeros` and `numpy.ones`.\n\nCreate an array of the given shape and populate it with\nrandom samples from a uniform distribution\nover ``[0, 1)``.\n\nParameters\n----------\nd0, d1, ..., dn : int, optional\n    The dimensions of the returned array, must be non-negative.\n    If no argument is given a single Python float is returned.\n\nReturns\n-------\nout : ndarray, shape ``(d0, d1, ..., dn)``\n    Random values.\n\nSee Also\n--------\nrandom\n\nExamples\n--------\n>>> np.random.rand(3,2)\narray([[ 0.14022471,  0.96360618],  #random\n       [ 0.37601032,  0.25528411],  #random\n       [ 0.49313049,  0.94909878]]) #random\n\n\n(*args: int) -> ndarray[Any, dtype[float64]

In [153]:
# RANDOM

# RAND - 0 va 1 oraligida berilgan shape boyicha tasodiviy sonlar
np.random.rand() 

0.20973090040039977

In [94]:
np.random.rand(2, 2, 2) 

array([[[0.74277047, 0.1008035 ],
        [0.5975872 , 0.21234437]],

       [[0.88535286, 0.69796426],
        [0.97701697, 0.22157943]]])

In [ ]:
"""
(low: int, high: int | None = ...) -> int
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the ``integers`` method of a ``default_rng()``
    instance instead; please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which case a
    single value is returned.
dtype : dtype, optional
    Desired dtype of the result. Byteorder must be native.
    The default value is int.

    .. versionadded:: 1.11.0

Returns
-------
out : int or ndarray of ints
    `size`-shaped array of random integers from the appropriate
    distribution, or a single such random int if `size` not provided.

See Also
--------
random_integers : similar to `randint`, only for the closed
    interval [`low`, `high`], and 1 is the lowest value if `high` is
    omitted.
Generator.integers: which should be used for new code.

Examples
--------
>>> np.random.randint(2, size=10)
array([1, 0, 0, 0, 1, 1, 0, 0, 1, 0]) # random
>>> np.random.randint(1, size=10)
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Generate a 2 x 4 array of ints between 0 and 4, inclusive:

>>> np.random.randint(5, size=(2, 4))
array([[4, 0, 2, 1], # random
       [3, 2, 2, 0]])

Generate a 1 x 3 array with 3 different upper bounds

>>> np.random.randint(1, [3, 5, 10])
array([2, 2, 9]) # random

Generate a 1 by 3 array with 3 different lower bounds

>>> np.random.randint([1, 5, 7], 10)
array([9, 8, 7]) # random

Generate a 2 by 4 array using broadcasting with dtype of uint8

>>> np.random.randint([1, 3, 5, 7], [[10], [20]], dtype=np.uint8)
array([[ 8,  6,  9,  7], # random
       [ 1, 16,  9, 12]], dtype=uint8)



(low: int, high: int | None = ..., size: None = ..., 
dtype: _DTypeLikeBool = ...) -> bool


(low: int, high: int | None = ..., 
size: None = ..., dtype: Type[int] | 
Type[signedinteger] | dtype[signedinteger] | 
_SupportsDType[dtype[signedinteger]] | 
Type[unsignedinteger] | 
dtype[unsignedinteger] |
 _SupportsDType[dtype[unsignedinteger]] |
  Literal['int8', 'i1', '=i1', '<i1', '>i1', 'int16', 
'i2', '=i2', '<i2', '>i2', 'int32',
 'i4', '=i4', '<i4', '>i4',
 'int64', 'i8', '=i8', '<i8', '>i8',
 'byte', 'b', '=b', '<b', '>b', 'short',
 'h', '=h', '<h', '>h', 'intc',
 'i', '=i', '<i', '>i', 'intp', 'int0',
 'p', '=p', '<p', '>p', 'long', 'int', 'int_',
 'l', '=l', '<l', '>l', 'longlong',
 'q', '=q', '<q', '>q', 'uint8',
 'u1', '=u1', '<u1', '>u1', 'uint16',
 'u2', '=u2', '<u2', '>u2', 'uint32',
 'u4', '=u4', '<u4', '>u4', 'uint64',
 'u8', '=u8', '<u8', '>u8', 'ubyte',
 'B', '=B', '<B', '>B', 'ushort',
 'H', '=H', '<H', '>H', 'uintc', 
'I', '=I', '<I', '>I',
 'uintp', 'uint0',
 'P', '=P', '<P', '>P', 'uint',
 'L', '=L', '<L', '>L', 'ulonglong',
 'Q', '=Q', '<Q', '>Q'] = ...) -> int




(low: _ArrayLikeInt_co, high: _ArrayLikeInt_co | None = ..., 
size: _ShapeLike | None = ...) -> ndarray[Any, dtype[int_]]


...

"""

In [98]:
# RANDOM

# RANDINT - 2 gacha, 10ta tasodiviy natural sonlar iborat array, 2 kirmaydi
np.random.randint(2, size=10)

array([1, 1, 1, 1, 0, 1, 1, 0, 1, 0])

In [99]:
# RANDINT - 1 gacha, 10ta tasodiviy natural sonlar iborat array, 1 kirmaydi
np.random.randint(1, size=10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [100]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [101]:
# RANDINT - 5 gacha, (2, 4) li tasodiviy natural sonlar iborat array, 5 kirmaydi
np.random.randint(5, size=(2, 4))

array([[2, 2, 0, 2],
       [1, 4, 3, 0]])

In [104]:
# RANDINT - pastki chegara - 1, yuqori chegara 3 ta uchun, 3, 5, 10 gacha va bu raqamlar kirmaydi
np.random.randint(1, [3, 5, 10])

array([2, 3, 8])

In [106]:
# RANDINT - pastki chegaralar - 1, 5, 7, yuqori chegara 10 gacha va bu raqamlar kirmaydi
np.random.randint([1, 5, 7], 10)

array([5, 7, 8])

In [109]:
# RANDINT - pastki chegara - ([1, 3, 5, 7], yuqori chegara [10], ikkinchi qator uchun [20]
np.random.randint([1, 3, 5, 7], [[10], [20]], dtype=np.uint8)

array([[ 6,  6,  8,  8],
       [ 3,  7, 19, 18]], dtype=uint8)

In [ ]:
"""
() -> float
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the ``standard_normal`` method of a ``default_rng()``
    instance instead; please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    If no argument is given a single Python float is returned.

Returns
-------
Z : ndarray or float
    A ``(d0, d1, ..., dn)``-shaped array of floating-point samples from
    the standard normal distribution, or a single such float if
    no parameters were supplied.

See Also
--------
standard_normal : Similar, but takes a tuple as its argument.
normal : Also accepts mu and sigma arguments.
Generator.standard_normal: which should be used for new code.

Notes
-----
For random samples from :math:`N(\mu, \sigma^2)`, use:

``sigma * np.random.randn(...) + mu``

Examples
--------
>>> np.random.randn()
2.1923875335537315  # random

Two-by-four array of samples from N(3, 6.25):

>>> 3 + 2.5 * np.random.randn(2, 4)
array([[-4.49401501,  4.00950034, -1.81814867,  7.29718677],   # random
       [ 0.39924804,  4.68456316,  4.99394529,  4.84057254]])  # random



(*args: int) -> ndarray[Any, dtype[float64]]
"""

In [154]:
np.random.randn(4, 4)

array([[-2.82294287,  1.04576413, -0.01339504,  0.27252857],
       [-0.00649293,  0.81238293, -0.29772269,  0.62353226],
       [ 0.57160643,  0.73486242,  2.64906183,  0.38111549],
       [ 0.33552162,  0.8400749 , -0.78775093,  0.32850872]])

---

In [114]:
arr = np.random.randn(7, 4)
arr

array([[-1.54568908,  0.50090851, -1.37765371,  0.0969461 ],
       [ 0.79467199, -0.7847479 , -0.6601733 , -0.21512645],
       [ 0.09881665,  0.96187625, -0.30830066, -1.46425082],
       [-1.74707006, -0.32710726, -1.61519979, -1.50114056],
       [-1.21505638, -0.41300639, -1.75047426,  0.95351273],
       [ 0.34459302, -1.1581315 , -1.2358987 ,  0.19654742],
       [-0.85540578,  0.96674027, -0.44505783,  2.63763946]])

In [121]:
names = np.array(['Jasur', 'Doston', 'Habib', 'Ikrom', 'Jasur', 'Sardor', 'Jamshid'])
names

array(['Jasur', 'Doston', 'Habib', 'Ikrom', 'Jasur', 'Sardor', 'Jamshid'],
      dtype='<U7')

In [122]:
names == 'Jasur'

array([ True, False, False, False,  True, False, False])

In [123]:
arr[names == 'Jasur']

array([[-1.54568908,  0.50090851, -1.37765371,  0.0969461 ],
       [-1.21505638, -0.41300639, -1.75047426,  0.95351273]])

In [125]:
arr[names == 'Jasur'][:2, 2:]

array([[-1.37765371,  0.0969461 ],
       [-1.75047426,  0.95351273]])

In [126]:
arr[names == 'Jasur', 2:]

array([[-1.37765371,  0.0969461 ],
       [-1.75047426,  0.95351273]])

In [128]:
names != 'Jasur'

array([False,  True,  True,  True, False,  True,  True])

In [129]:
arr[names != 'Jasur']

array([[ 0.79467199, -0.7847479 , -0.6601733 , -0.21512645],
       [ 0.09881665,  0.96187625, -0.30830066, -1.46425082],
       [-1.74707006, -0.32710726, -1.61519979, -1.50114056],
       [ 0.34459302, -1.1581315 , -1.2358987 ,  0.19654742],
       [-0.85540578,  0.96674027, -0.44505783,  2.63763946]])

In [130]:
(names == 'Jasur') | (names == 'Ikrom')

array([ True, False, False,  True,  True, False, False])

In [132]:
arr[(names == 'Jasur') | (names == 'Ikrom')]

array([[-1.54568908,  0.50090851, -1.37765371,  0.0969461 ],
       [-1.74707006, -0.32710726, -1.61519979, -1.50114056],
       [-1.21505638, -0.41300639, -1.75047426,  0.95351273]])

In [133]:
arr[~((names == 'Jasur') | (names == 'Ikrom'))]

array([[ 0.79467199, -0.7847479 , -0.6601733 , -0.21512645],
       [ 0.09881665,  0.96187625, -0.30830066, -1.46425082],
       [ 0.34459302, -1.1581315 , -1.2358987 ,  0.19654742],
       [-0.85540578,  0.96674027, -0.44505783,  2.63763946]])

In [134]:
arr

array([[-1.54568908,  0.50090851, -1.37765371,  0.0969461 ],
       [ 0.79467199, -0.7847479 , -0.6601733 , -0.21512645],
       [ 0.09881665,  0.96187625, -0.30830066, -1.46425082],
       [-1.74707006, -0.32710726, -1.61519979, -1.50114056],
       [-1.21505638, -0.41300639, -1.75047426,  0.95351273],
       [ 0.34459302, -1.1581315 , -1.2358987 ,  0.19654742],
       [-0.85540578,  0.96674027, -0.44505783,  2.63763946]])

In [136]:
arr[arr>0]

array([0.50090851, 0.0969461 , 0.79467199, 0.09881665, 0.96187625,
       0.95351273, 0.34459302, 0.19654742, 0.96674027, 2.63763946])

In [147]:
arr[arr>0] = 111

In [148]:
arr

array([[ -1., 111.,  -1., 111.],
       [111.,  -1.,  -1.,  -1.],
       [111., 111.,  -1.,  -1.],
       [ -1.,  -1.,  -1.,  -1.],
       [ -1.,  -1.,  -1., 111.],
       [111.,  -1.,  -1., 111.],
       [ -1., 111.,  -1., 111.]])

In [149]:
arr[arr<0]

array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1.])

In [151]:
arr[arr<0] = 0

In [152]:
arr

array([[  0., 111.,   0., 111.],
       [111.,   0.,   0.,   0.],
       [111., 111.,   0.,   0.],
       [  0.,   0.,   0.,   0.],
       [  0.,   0.,   0., 111.],
       [111.,   0.,   0., 111.],
       [  0., 111.,   0., 111.]])

---

In [155]:
arr.T

array([[  0., 111., 111.,   0.,   0., 111.,   0.],
       [111.,   0., 111.,   0.,   0.,   0., 111.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [111.,   0.,   0.,   0., 111., 111., 111.]])

In [156]:
arr

array([[  0., 111.,   0., 111.],
       [111.,   0.,   0.,   0.],
       [111., 111.,   0.,   0.],
       [  0.,   0.,   0.,   0.],
       [  0.,   0.,   0., 111.],
       [111.,   0.,   0., 111.],
       [  0., 111.,   0., 111.]])

In [160]:
arr.swapaxes(1, 0)

array([[  0., 111., 111.,   0.,   0., 111.,   0.],
       [111.,   0., 111.,   0.,   0.,   0., 111.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [111.,   0.,   0.,   0., 111., 111., 111.]])

In [161]:
np.dot(arr, arr.T)

array([[24642.,     0., 12321.,     0., 12321., 12321., 24642.],
       [    0., 12321., 12321.,     0.,     0., 12321.,     0.],
       [12321., 12321., 24642.,     0.,     0., 12321., 12321.],
       [    0.,     0.,     0.,     0.,     0.,     0.,     0.],
       [12321.,     0.,     0.,     0., 12321., 12321., 12321.],
       [12321., 12321., 12321.,     0., 12321., 24642., 12321.],
       [24642.,     0., 12321.,     0., 12321., 12321., 24642.]])

---

In [ ]:
# UNARY
# np.sqrt()
# np.square()
# np.exp()
# np.log(), log2(), log10(), log1p - log(1+x)
# np.log(arr[1:])
# np.modf() - qoldiq, butun
# np.sign() - >0 1, <0 -1
# np.isnan()
# np.abs(), fabs() - absolut qiymat, modul
# np.ceil()
# np.floor()
# np.rint() - yaxlitlaydi
# np.cos()
# np.arccos()

In [ ]:
# BINARY
# np.add()
# np.subtract()
# np.multiply()
# np.maximum
# np.power() -- **
# max, fmax
# min, fmin
# mod
# copysign
# greater, greater_equal, less, less_equal, equal, not_equal
# logical_and, logical_or, logical_xor -- &, |, ^

In [165]:
arr

array([[  0., 111.,   0., 111.],
       [111.,   0.,   0.,   0.],
       [111., 111.,   0.,   0.],
       [  0.,   0.,   0.,   0.],
       [  0.,   0.,   0., 111.],
       [111.,   0.,   0., 111.],
       [  0., 111.,   0., 111.]])

In [166]:
arr.size

28

In [169]:
len(arr)

7

In [170]:
arr3d

array([[[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[31, 32, 33],
        [34, 35, 36],
        [37, 38, 39]]])

In [171]:
len(arr3d)

3

In [174]:
arr[arr==0.] = 5
arr

array([[  5., 111.,   5., 111.],
       [111.,   5.,   5.,   5.],
       [111., 111.,   5.,   5.],
       [  5.,   5.,   5.,   5.],
       [  5.,   5.,   5., 111.],
       [111.,   5.,   5., 111.],
       [  5., 111.,   5., 111.]])

In [175]:
np.cumprod(arr)

array([5.00000000e+00, 5.55000000e+02, 2.77500000e+03, 3.08025000e+05,
       3.41907750e+07, 1.70953875e+08, 8.54769375e+08, 4.27384688e+09,
       4.74397003e+11, 5.26580673e+13, 2.63290337e+14, 1.31645168e+15,
       6.58225842e+15, 3.29112921e+16, 1.64556460e+17, 8.22782302e+17,
       4.11391151e+18, 2.05695576e+19, 1.02847788e+20, 1.14161044e+22,
       1.26718759e+24, 6.33593797e+24, 3.16796898e+25, 3.51644557e+27,
       1.75822279e+28, 1.95162729e+30, 9.75813646e+30, 1.08315315e+33])

In [176]:
np.sort(arr)

array([[  5.,   5., 111., 111.],
       [  5.,   5.,   5., 111.],
       [  5.,   5., 111., 111.],
       [  5.,   5.,   5.,   5.],
       [  5.,   5.,   5., 111.],
       [  5.,   5., 111., 111.],
       [  5.,   5., 111., 111.]])

In [177]:
arr

array([[  5., 111.,   5., 111.],
       [111.,   5.,   5.,   5.],
       [111., 111.,   5.,   5.],
       [  5.,   5.,   5.,   5.],
       [  5.,   5.,   5., 111.],
       [111.,   5.,   5., 111.],
       [  5., 111.,   5., 111.]])

In [179]:
np.sort(arr, axis=0)

array([[  5.,   5.,   5.,   5.],
       [  5.,   5.,   5.,   5.],
       [  5.,   5.,   5.,   5.],
       [  5.,   5.,   5., 111.],
       [111., 111.,   5., 111.],
       [111., 111.,   5., 111.],
       [111., 111.,   5., 111.]])

In [180]:
np.unique(arr)

array([  5., 111.])

In [181]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [183]:
# arr2d ning har bir elementini arrda bormi yoqmi tekshiradi va orniga True / False qoyadi
np.in1d(arr2d, arr)

array([False, False, False, False,  True, False, False, False, False])

In [184]:
# arr2d ning har bir elementini arrda bormi yoqmi tekshiradi va arrda yoqini ajratib oladi
np.setdiff1d(arr2d, arr)

array([1, 2, 3, 4, 6, 7, 8, 9])

In [185]:
# arr ning har bir elementini arr2dda bormi yoqmi tekshiradi va arr2dda yoqini ajratib oladi
np.setdiff1d(arr, arr2d)

array([111.])

In [187]:
arr = np.arange(6).reshape(2, 3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [189]:
arr2d = np.random.randint(10, size=(2, 3))
arr2d

array([[1, 5, 6],
       [9, 0, 1]])

In [190]:
arr * arr2d

array([[ 0,  5, 12],
       [27,  0,  5]])

In [191]:
arr2d * arr

array([[ 0,  5, 12],
       [27,  0,  5]])

In [193]:
np.dot(arr, arr2d.T)

array([[17,  2],
       [53, 32]])

In [196]:
np.dot(arr2d, arr.T)

array([[17, 53],
       [ 2, 32]])

In [195]:
np.dot(arr2d.T, arr)

array([[27, 37, 47],
       [ 0,  5, 10],
       [ 3, 10, 17]])

In [194]:
np.dot(arr.T, arr2d)

array([[27,  0,  3],
       [37,  5, 10],
       [47, 10, 17]])