<a href="https://colab.research.google.com/github/jfcoderx/Data-Sciense/blob/main/TAKRORLASH_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [101]:
import pandas as pd
import numpy as np

In [102]:
ser1 = pd.Series([-1, 2, 3.3, 44, 0])
ser1

0    -1.0
1     2.0
2     3.3
3    44.0
4     0.0
dtype: float64

In [103]:
-1.0 in ser1

False

In [104]:
type(ser1)

pandas.core.series.Series

In [105]:
ser1.values

array([-1. ,  2. ,  3.3, 44. ,  0. ])

In [106]:
type(ser1.values)

numpy.ndarray

In [107]:
ser1.index

RangeIndex(start=0, stop=5, step=1)

In [108]:
ser1.ndim

1

In [109]:
ser1[0]

-1.0

In [110]:
ser2 = pd.Series([0, 0, 0, 0], [-3, -4, -5, -6])
ser2

-3    0
-4    0
-5    0
-6    0
dtype: int64

In [111]:
ser2.index

Int64Index([-3, -4, -5, -6], dtype='int64')

In [112]:
ser2.ndim

1

In [113]:
ser2[-5] = 111
ser2

-3      0
-4      0
-5    111
-6      0
dtype: int64

In [114]:
ser2[[-3, -6, -4]]

-3    0
-6    0
-4    0
dtype: int64

In [115]:
ser2[ser2>0]

-5    111
dtype: int64

In [116]:
ser2[ser2==0] = -111
ser2

-3   -111
-4   -111
-5    111
-6   -111
dtype: int64

In [117]:
ser2 ** 2

-3    12321
-4    12321
-5    12321
-6    12321
dtype: int64

In [118]:
ser1 = pd.Series({'A': 40, 'B': 20, 'C': 45, 'D': 52, 'E': 38})
ser1

A    40
B    20
C    45
D    52
E    38
dtype: int64

In [119]:
cars = pd.Series({'Malibu': 40000, 'Lasetti': 20000, 'Toyota': 45000, 'Mazda': 52000, 'Honda': 38000})
cars

Malibu     40000
Lasetti    20000
Toyota     45000
Mazda      52000
Honda      38000
dtype: int64

In [120]:
# faqat indeks va indeksni bilish uchun
"Toyota" in cars

True

In [121]:
'BMW' in cars

False

In [122]:
40000 in cars

False

In [123]:
pd.Series(cars, index=['J', 'M', 'C'])

J   NaN
M   NaN
C   NaN
dtype: float64

In [124]:
cars2 = pd.Series(cars, index=['Malibu', 'J', 'Mazda', 'M', 'C',  'Lasetti', 'Toyota', 'Honda'])
cars2

Malibu     40000.0
J              NaN
Mazda      52000.0
M              NaN
C              NaN
Lasetti    20000.0
Toyota     45000.0
Honda      38000.0
dtype: float64

In [125]:
cars.ndim

1

In [126]:
cars.isnull()

Malibu     False
Lasetti    False
Toyota     False
Mazda      False
Honda      False
dtype: bool

In [127]:
cars2.isnull()

Malibu     False
J           True
Mazda      False
M           True
C           True
Lasetti    False
Toyota     False
Honda      False
dtype: bool

In [128]:
cars2.notnull()

Malibu      True
J          False
Mazda       True
M          False
C          False
Lasetti     True
Toyota      True
Honda       True
dtype: bool

In [129]:
cars + cars2

C               NaN
Honda       76000.0
J               NaN
Lasetti     40000.0
M               NaN
Malibu      80000.0
Mazda      104000.0
Toyota      90000.0
dtype: float64

In [130]:
cars.name = 'CARS'
cars.index.name = 'MODELS'
cars

MODELS
Malibu     40000
Lasetti    20000
Toyota     45000
Mazda      52000
Honda      38000
Name: CARS, dtype: int64

In [131]:
cars2.name = 'CARS 2'
cars2.index.name = 'MODELS 2'
cars2

MODELS 2
Malibu     40000.0
J              NaN
Mazda      52000.0
M              NaN
C              NaN
Lasetti    20000.0
Toyota     45000.0
Honda      38000.0
Name: CARS 2, dtype: float64

In [132]:
cars.hasnans

False

In [133]:
cars2.hasnans

True

In [134]:
cars['mmmmmmm'] = 100
cars

MODELS
Malibu     40000
Lasetti    20000
Toyota     45000
Mazda      52000
Honda      38000
mmmmmmm      100
Name: CARS, dtype: int64

In [135]:
cars2['Mazda'] = 10
cars2

MODELS 2
Malibu     40000.0
J              NaN
Mazda         10.0
M              NaN
C              NaN
Lasetti    20000.0
Toyota     45000.0
Honda      38000.0
Name: CARS 2, dtype: float64

In [136]:
cars.is_unique

True

In [137]:
cars2.is_unique

False

In [138]:
cars.size

6

In [139]:
cars2.size

8

In [140]:
cars.shape

(6,)

In [141]:
cars2.shape

(8,)

In [142]:
cars[1]

20000

In [143]:
cars[-1]

100

In [144]:
cars.iloc[1]

20000

In [145]:
cars.iloc[-1]

100

In [146]:
data = {
    'Yil': [2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014],
    'Aholi soni': [33.9, 33.5, 32.9, 32.5, 31.9, 31.4, 30.9, 28.5],
    'Temp': [1.54, 1.48, 1.56, 1.62, 1.65, 1.66, 1.64, 1.53]
}

In [147]:
df_ser = pd.Series(data)
df_ser

Yil           [2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014]
Aholi soni    [33.9, 33.5, 32.9, 32.5, 31.9, 31.4, 30.9, 28.5]
Temp          [1.54, 1.48, 1.56, 1.62, 1.65, 1.66, 1.64, 1.53]
dtype: object

In [148]:
df_ser.ndim

1

In [149]:
df_ser.T

Yil           [2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014]
Aholi soni    [33.9, 33.5, 32.9, 32.5, 31.9, 31.4, 30.9, 28.5]
Temp          [1.54, 1.48, 1.56, 1.62, 1.65, 1.66, 1.64, 1.53]
dtype: object

In [150]:
type(df_ser)

pandas.core.series.Series

---

In [151]:
pd.DataFrame([-1, 2, 3.3, 44, 0])

0
0  -1.0
1   2.0
2   3.3
3  44.0
4   0.0

In [152]:
df = pd.DataFrame(data)
df

Yil  Aholi soni  Temp
0  2021        33.9  1.54
1  2020        33.5  1.48
2  2019        32.9  1.56
3  2018        32.5  1.62
4  2017        31.9  1.65
5  2016        31.4  1.66
6  2015        30.9  1.64
7  2014        28.5  1.53

In [153]:
type(df)

pandas.core.frame.DataFrame

In [154]:
df.T

0        1        2        3        4        5        6  \
Yil         2021.00  2020.00  2019.00  2018.00  2017.00  2016.00  2015.00   
Aholi soni    33.90    33.50    32.90    32.50    31.90    31.40    30.90   
Temp           1.54     1.48     1.56     1.62     1.65     1.66     1.64   

                  7  
Yil         2014.00  
Aholi soni    28.50  
Temp           1.53

In [155]:
pd.DataFrame(data, ['A', 'B', 'C', 'D', 'F', 'J', 'K', 'E'])
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [156]:
a = pd.DataFrame({
                'Yil': {'A': 2021, 'B': 2020, 'C': 2019, 'D': 2018, 'F': 2017, 'J': 2016, 'K': 2015, 'E': 2014},
                'Aholi soni': {'A': 33.9, 'B': 33.5, 'C': 32.9, 'D': 32.5, 'F': 31.9, 'J': 31.4, 'K': 30.9, 'E': 28.5},
                'Temp': {1: 1.54, 2: 1.48, 3: 1.56, 4: 1.62, 5: 1.65, 6: 1.66, 7: 1.64, 8: 1.53}
            })
a

Yil  Aholi soni  Temp
A  2021.0        33.9   NaN
B  2020.0        33.5   NaN
C  2019.0        32.9   NaN
D  2018.0        32.5   NaN
F  2017.0        31.9   NaN
J  2016.0        31.4   NaN
K  2015.0        30.9   NaN
E  2014.0        28.5   NaN
1     NaN         NaN  1.54
2     NaN         NaN  1.48
3     NaN         NaN  1.56
4     NaN         NaN  1.62
5     NaN         NaN  1.65
6     NaN         NaN  1.66
7     NaN         NaN  1.64
8     NaN         NaN  1.53

In [157]:
a.T

A       B       C       D       F       J       K       E  \
Yil         2021.0  2020.0  2019.0  2018.0  2017.0  2016.0  2015.0  2014.0   
Aholi soni    33.9    33.5    32.9    32.5    31.9    31.4    30.9    28.5   
Temp           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

               1     2     3     4     5     6     7     8  
Yil          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
Aholi soni   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
Temp        1.54  1.48  1.56  1.62  1.65  1.66  1.64  1.53

In [158]:
df.ndim

2

In [159]:
df.head()

Yil  Aholi soni  Temp
0  2021        33.9  1.54
1  2020        33.5  1.48
2  2019        32.9  1.56
3  2018        32.5  1.62
4  2017        31.9  1.65

In [160]:
df.shape

(8, 3)

In [161]:
df

Yil  Aholi soni  Temp
0  2021        33.9  1.54
1  2020        33.5  1.48
2  2019        32.9  1.56
3  2018        32.5  1.62
4  2017        31.9  1.65
5  2016        31.4  1.66
6  2015        30.9  1.64
7  2014        28.5  1.53

In [162]:
data

{'Yil': [2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014],
 'Aholi soni': [33.9, 33.5, 32.9, 32.5, 31.9, 31.4, 30.9, 28.5],
 'Temp': [1.54, 1.48, 1.56, 1.62, 1.65, 1.66, 1.64, 1.53]}

In [163]:
pd.DataFrame(data, columns=["aaa", "bbb", 'CCC', 231])

Empty DataFrame
Columns: [aaa, bbb, CCC, 231]
Index: []

In [164]:
df['Temp']

0    1.54
1    1.48
2    1.56
3    1.62
4    1.65
5    1.66
6    1.64
7    1.53
Name: Temp, dtype: float64

In [165]:
type(df['Temp'])

pandas.core.series.Series

In [166]:
df.iloc[0]

Yil           2021.00
Aholi soni      33.90
Temp             1.54
Name: 0, dtype: float64

In [167]:
df['Tugulishlar_Soni'] = [1700, 1800, 2000, 3000, 2222, 1111, 4444, 5555]
df

Yil  Aholi soni  Temp  Tugulishlar_Soni
0  2021        33.9  1.54              1700
1  2020        33.5  1.48              1800
2  2019        32.9  1.56              2000
3  2018        32.5  1.62              3000
4  2017        31.9  1.65              2222
5  2016        31.4  1.66              1111
6  2015        30.9  1.64              4444
7  2014        28.5  1.53              5555

In [168]:
df['new colunmn'] = df.Temp > 1.6
df

Yil  Aholi soni  Temp  Tugulishlar_Soni  new colunmn
0  2021        33.9  1.54              1700        False
1  2020        33.5  1.48              1800        False
2  2019        32.9  1.56              2000        False
3  2018        32.5  1.62              3000         True
4  2017        31.9  1.65              2222         True
5  2016        31.4  1.66              1111         True
6  2015        30.9  1.64              4444         True
7  2014        28.5  1.53              5555        False

In [169]:
df.index.name = 'Numbers'
df

Yil  Aholi soni  Temp  Tugulishlar_Soni  new colunmn
Numbers                                                       
0        2021        33.9  1.54              1700        False
1        2020        33.5  1.48              1800        False
2        2019        32.9  1.56              2000        False
3        2018        32.5  1.62              3000         True
4        2017        31.9  1.65              2222         True
5        2016        31.4  1.66              1111         True
6        2015        30.9  1.64              4444         True
7        2014        28.5  1.53              5555        False

In [170]:
df.T

Numbers               0      1      2     3     4     5     6      7
Yil                2021   2020   2019  2018  2017  2016  2015   2014
Aholi soni         33.9   33.5   32.9  32.5  31.9  31.4  30.9   28.5
Temp               1.54   1.48   1.56  1.62  1.65  1.66  1.64   1.53
Tugulishlar_Soni   1700   1800   2000  3000  2222  1111  4444   5555
new colunmn       False  False  False  True  True  True  True  False

In [171]:
df.index

RangeIndex(start=0, stop=8, step=1, name='Numbers')

In [172]:
df.values

array([[2021, 33.9, 1.54, 1700, False],
       [2020, 33.5, 1.48, 1800, False],
       [2019, 32.9, 1.56, 2000, False],
       [2018, 32.5, 1.62, 3000, True],
       [2017, 31.9, 1.65, 2222, True],
       [2016, 31.4, 1.66, 1111, True],
       [2015, 30.9, 1.64, 4444, True],
       [2014, 28.5, 1.53, 5555, False]], dtype=object)

In [173]:
df.index[0]

0

In [174]:
indexa = pd.Index(['p', 'i', 1, 3, 'o'])
indexa

Index(['p', 'i', 1, 3, 'o'], dtype='object')

In [175]:
indexa.isin(df.index)

array([False, False,  True,  True, False])

In [176]:
indexa.difference(df.index)

Index(['i', 'o', 'p'], dtype='object')

In [177]:
df.index.difference(indexa)

Int64Index([0, 2, 4, 5, 6, 7], dtype='int64')

In [178]:
df.index.union(indexa)

Index([0, 1, 2, 3, 4, 5, 6, 7, 'i', 'o', 'p'], dtype='object')

In [179]:
indexa.union(df.index)

Index([0, 1, 2, 3, 4, 5, 6, 7, 'i', 'o', 'p'], dtype='object')

In [180]:
df

Yil  Aholi soni  Temp  Tugulishlar_Soni  new colunmn
Numbers                                                       
0        2021        33.9  1.54              1700        False
1        2020        33.5  1.48              1800        False
2        2019        32.9  1.56              2000        False
3        2018        32.5  1.62              3000         True
4        2017        31.9  1.65              2222         True
5        2016        31.4  1.66              1111         True
6        2015        30.9  1.64              4444         True
7        2014        28.5  1.53              5555        False

In [181]:
df.index.delete(5)

Int64Index([0, 1, 2, 3, 4, 6, 7], dtype='int64', name='Numbers')

In [182]:
df

Yil  Aholi soni  Temp  Tugulishlar_Soni  new colunmn
Numbers                                                       
0        2021        33.9  1.54              1700        False
1        2020        33.5  1.48              1800        False
2        2019        32.9  1.56              2000        False
3        2018        32.5  1.62              3000         True
4        2017        31.9  1.65              2222         True
5        2016        31.4  1.66              1111         True
6        2015        30.9  1.64              4444         True
7        2014        28.5  1.53              5555        False

In [183]:
df.index

RangeIndex(start=0, stop=8, step=1, name='Numbers')

In [184]:
indexa.drop('o')

Index(['p', 'i', 1, 3], dtype='object')

In [185]:
df.index.insert(2, 'ttt')

Index([0, 1, 'ttt', 2, 3, 4, 5, 6, 7], dtype='object', name='Numbers')

In [186]:
df

Yil  Aholi soni  Temp  Tugulishlar_Soni  new colunmn
Numbers                                                       
0        2021        33.9  1.54              1700        False
1        2020        33.5  1.48              1800        False
2        2019        32.9  1.56              2000        False
3        2018        32.5  1.62              3000         True
4        2017        31.9  1.65              2222         True
5        2016        31.4  1.66              1111         True
6        2015        30.9  1.64              4444         True
7        2014        28.5  1.53              5555        False

In [187]:
indexa.is_unique

True

In [188]:
df.index.is_unique

True

In [189]:
df.index.is_monotonic

True

In [190]:
df.index.unique

<bound method Index.unique of RangeIndex(start=0, stop=8, step=1, name='Numbers')>

---
---