<a href="https://colab.research.google.com/github/jfcoderx/Data-Sciense/blob/main/takrorlash1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
from numpy import array, zeros, ones, zeros_like, ones_like, empty, empty_like, full, full_like, eye, identity

In [9]:
from numpy.core.numeric import array_equal
data1 = [1, 2, 3, 4]
data2 = (1, 2, 3, 4)
arr_list = array(data1)
arr_tuple = array(data2)

In [10]:
arr_list

array([1, 2, 3, 4])

In [11]:
arr_tuple

array([1, 2, 3, 4])

In [13]:
data3 = [[1, 2], [3, 4]]
data4 = ((1, 2), (3, 4))

arr_list_2d = array(data3)
arr_tuple_2d = array(data4)

In [14]:
arr_list_2d

array([[1, 2],
       [3, 4]])

In [16]:
arr_tuple_2d

array([[1, 2],
       [3, 4]])

In [18]:
data5 = [
          [
              [1, 2], [3, 4]
          ], 
          [
              [5, 6], [7, 8]
          ]
        ]
arr_3d = array(data5)
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [19]:
arr_3d.ndim

3

In [20]:
print(arr_list_2d.shape)
print(arr_list_2d.size)
print(arr_list_2d.shape)
print(arr_list_2d.size)
print(arr_3d.shape)
print(arr_3d.size)

(2, 2)
4
(2, 2)
4
(2, 2, 2)
8


In [24]:
arr_zeros = zeros((4, 4))
arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
arr_zeros_like = zeros_like(arr_3d)
arr_zeros_like

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [25]:
arr_ones = ones((4, 4))
arr_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
arr_ones_like = ones_like(arr_3d)
arr_ones_like

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [33]:
arr_ones_3d = ones((3, 3, 3))
arr_ones_3d

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [36]:
arr_empty = empty((2, 2))
arr_empty

array([[4.9e-324, 9.9e-324],
       [1.5e-323, 2.0e-323]])

In [37]:
arr_empty_3d = empty((3, 3, 3))
arr_empty_3d

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [38]:
arr_empty_like = empty_like(arr_3d)
arr_empty_like

array([[[4607182418800017408, 4607182418800017408],
        [4607182418800017408, 4607182418800017408]],

       [[4607182418800017408, 4607182418800017408],
        [4607182418800017408, 4607182418800017408]]])

In [44]:
arr_full_44 = full([2, 2], 44)
arr_full_44

array([[44, 44],
       [44, 44]])

In [50]:
arr_full_like = full_like(arr_3d, 44)
arr_full_like

array([[[44, 44],
        [44, 44]],

       [[44, 44],
        [44, 44]]])

In [52]:
arr_eye = eye(5)
arr_eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
arr_eye.ndim

2

In [54]:
arr_identify = identity(5)
arr_identify

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [55]:
arr_identify.ndim

2