## NumPy Array

Demak vektorlashgan hisoblashlar massivlar ustida amalga oshirilar ekan

In [1]:
import numpy as np

N o'lchamli massiv (array) larga ishlov berish

NumPyda massiv yaratishning eng oson yo'llaridan biri ARRAY funksiyasi yordamida bajariladi.
Bu funksiya har qanday turdagi ketma ket ma'lumotlarni qabul qilib, uni yangi NumPy ga ogirib beradi

In [2]:
data1 = [3.4, 2, 4, -1, 99] # list
arr1 = np.array(data1) # array 1

In [3]:
data1

[3.4, 2, 4, -1, 99]

In [4]:
arr1

array([ 3.4,  2. ,  4. , -1. , 99. ])

In [5]:
data2 = (2, 3, 5, 0.3, -1) # tuple
arr2 = np.array(data2) # array 2

In [6]:
data2

(2, 3, 5, 0.3, -1)

In [7]:
arr2

array([ 2. ,  3. ,  5. ,  0.3, -1. ])

Massiv o'lchami aniqlash:

In [8]:
arr1.ndim # array 1 ning o'lchami

1

In [9]:
arr2.ndim # array 2 ning o'lchami

1

### endi 2-o'lchamli massivlarni yaratishni ko'ramiz
### bu orqali qanday qilib n o'lchamli massivlar yaratishni bilib olamiz

### 2 va undan katta o'lchamli massivlar:
bunda listdan foydalanamiz, nested listdan
list ichida listlardan

In [10]:
data3 = [[1, 2, 3, 4], [5, 6, 7, 8]] # list ichidagi list (nested list)
arr3 = np.array(data3)

In [12]:
data3

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [13]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr3.ndim

2

In [19]:
data4 = [
            [
                [11, 12, 13], [14, 15, 16], [17, 18, 19]
            ],
            [
                [21, 22, 23], [24, 25, 26], [27, 28, 29]
            ],
            [
                [31, 32, 33], [34, 35, 36], [37, 38, 39]
            ]
        ]
arr4 = np.array(data4)

In [20]:
data4

[[[11, 12, 13], [14, 15, 16], [17, 18, 19]],
 [[21, 22, 23], [24, 25, 26], [27, 28, 29]],
 [[31, 32, 33], [34, 35, 36], [37, 38, 39]]]

In [21]:
arr4

array([[[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[31, 32, 33],
        [34, 35, 36],
        [37, 38, 39]]])

In [22]:
arr4.ndim

3

## Foydali metodlar
shape, size metodlari

shape metodi - massivning qator va ustunlarini ko'rsatib berarkan
size metodi - massivimizdagi barcha elementlarimiz sonini ko'rsatadi

In [24]:
arr3.shape # qator va ustunlar soni (qator, ustun) tuple ko'rinishida

(2, 4)

In [25]:
arr3.size #

8

In [26]:
arr4.shape

(3, 3, 3)

In [27]:
arr4.size

27


## N o'lchamli massivlarni yaratishning boshqa usullari

zeros
ones
funksiyalari yordamida

zeros, barcha elementlari NOLDAN tashkil topgan massivlarni yaratishga yordam beradi
ones, barcha elementlari BIRDAN tashkil topgan massivlarni yaratishga yordam beradi


In [29]:
arr5 = np.zeros(shape=(3, 3)) # 3 ta ustun va 3 ta qatorli nol massivlar
arr5

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
arr6 = np.ones((4, 4)) # 4 ta ustun va 4 ta qatorli bir massivlar
arr6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

arange()

arange funksiyasi - pythondagi range() funksiyasi bilan deyarli bir xil
birdan bir farqi massivlar yaratishda qo'llaniladi VA natija sifatida array korinish qaytaradi

In [33]:
arr7 = np.arange(4, 20, 2) # 4 dan 20 gacha qiymatlarni 2 qadam bilan massivga joylab beradi, 20 kirmaydi
arr7

array([ 4,  6,  8, 10, 12, 14, 16, 18])

### zeros_like
boshqa arrayni qabul qilib, uning shakli (shape) va malumot turi (dtype) bilan bir xil
ammo elementlari NOL ga teng ndarray qaytaradi

In [34]:
arr8 = np.zeros_like(arr7)
arr8

array([0, 0, 0, 0, 0, 0, 0, 0])

### empty, empty_like
Yangi array hosil qilib, ammo ZEROS va ONES kabi aniq qiymatlarga ega bolmagan array qaytaradi

In [36]:
arr9 = np.empty((2,2))
arr9

array([[1.27000123e-311, 1.27000123e-311],
       [1.27000109e-311, 1.27000109e-311]])

In [37]:
arr10 = np.empty_like(arr8)
arr10

array([2120658224,        598, 2120658288,        598, 2120387376,
              598, 2120384624,        598])

### full
Berilgan malumot shakli (shape) ga kora barcha elementlari
"fil_value" iborat arrayni qaytaradi

### full_like
Boshqa arrayni qabul qilib, uning shakli (shape) va ma'lumot turi (dtype) bilan bir xil,
ammo elementlari "fil_value" ga teng bo'lgan ndarray qaytaradi

In [39]:
arr11 = np.full([2,4], 5)
arr11

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [42]:
arr12 = np.full_like(arr8, 212)
arr12

array([212, 212, 212, 212, 212, 212, 212, 212])

### eye, identity

NxN kvadrat o'lchamidagi matritsa yaratadi (diagonal elementlari, 1 lardan
qolgan elementlari 0 lardan tashkil topadi

In [44]:
arr12 = np.eye(5)
arr12

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
arr13 = np.eye(5, 3)
arr13

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
arr14 = np.identity(4)
arr14

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])