<a href="https://colab.research.google.com/github/jfcoderx/Data-Sciense/blob/main/4_Bolean_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Boolean indexlash

In [2]:
import numpy as np

In [8]:
# ismlar
names = np.array(['Jasur', 'Doston', 'Habib', 'Ikrom', 'Jasur', 'Sardor', 'Jamshid'])
names

array(['Jasur', 'Doston', 'Habib', 'Ikrom', 'Jasur', 'Sardor', 'Jamshid'],
      dtype='<U7')

In [10]:
# data
data = np.random.randn(7, 4) # istalgan malumotlar turi, 7 qatorli, 4 ustunli
data

array([[-0.37496467,  0.67438124,  0.28814237, -0.6230284 ],
       [-0.95914298, -0.3807025 ,  0.51446469,  1.33437546],
       [-0.90967151,  0.21212172,  0.09479158,  1.49019764],
       [ 0.51971308,  2.5688994 ,  0.79056676, -0.60713384],
       [ 0.3093182 , -1.07644966,  0.40523114,  0.54613115],
       [-0.91013178,  1.56100127,  0.09453718, -0.26293626],
       [ 1.22353034, -1.39566492, -0.02244134,  1.52808094]])

Boolean indekslash bu Massiv elementlarining indekslari, boolean malumot turlaridan tashkil topgan yani True Falselardan

Dastlab massivlardan iborat massivimizni indekslarini boolean korinishga otkazib olamiz:

In [11]:
names == 'Jasur'

array([ True, False, False, False,  True, False, False])

names massivimizni ana endi boolean korinishidagi massivimizga ogirib oldik, True degani ikki marta qaytarilgan chunki bizda 'Jasur' degan malumotimiz ikta bo'lgani uchun

Ana endi mana shu boolean indeksimizdan foydalanib biz, data nomli malumotlarimizdan aynan 'Jasur' ismli kishiga tegishli malumotlarni ajratib olamiz, bu uchun data massimizga indek sifatida boolean indeksimizni kiritamiz


In [13]:
data[names == 'Jasur'] # bu degani barcha Jasurga tegishli malumotlarni datadan kesib ol degani

array([[-0.37496467,  0.67438124,  0.28814237, -0.6230284 ],
       [ 0.3093182 , -1.07644966,  0.40523114,  0.54613115]])

korinib turibdi 2 qator malumotlarni ajratib olindi, yani indeksi True indeksga mos tushadigan malumotlarni ajratib olindi, buni boshqa ismlar orqali ham qo'lasak boladi <br><br>

misolga yanada chuqurlashadigan bo'lsak
data[names == 'Jasur'] bu chiqarilgan malumotlarni (2, 2) tipidagi malumotlarni ajratib chiqaraylik

In [15]:
data[names == 'Jasur'][:2, 2:] 

array([[ 0.28814237, -0.6230284 ],
       [ 0.40523114,  0.54613115]])

In [16]:
data[names == 'Jasur', 2:] # qatorlar soni mak bolagni uchun belgilanmadi, ustunlar soni esa 2dan oxiriga, shularga togri keluvchi malumotlarni ajratib olish
# Jasurga tegishli oxirgi ikkita ustundagi malumotlarni ajratib olish

array([[ 0.28814237, -0.6230284 ],
       [ 0.40523114,  0.54613115]])

Jasurga tegishli bolmagan malumotlarni ham ajratib olish mumkin, NOT EQUAL amalidan foydalanamiz


In [17]:
data[names != 'Jasur'] # Jasurdan tashqari barcha insonlarning malumotlari --> (!=)

array([[-0.95914298, -0.3807025 ,  0.51446469,  1.33437546],
       [-0.90967151,  0.21212172,  0.09479158,  1.49019764],
       [ 0.51971308,  2.5688994 ,  0.79056676, -0.60713384],
       [-0.91013178,  1.56100127,  0.09453718, -0.26293626],
       [ 1.22353034, -1.39566492, -0.02244134,  1.52808094]])

In [18]:
data[~(names == 'Jasur')] # Yuroridagi cell bilan bir xil natija --> (~)

array([[-0.95914298, -0.3807025 ,  0.51446469,  1.33437546],
       [-0.90967151,  0.21212172,  0.09479158,  1.49019764],
       [ 0.51971308,  2.5688994 ,  0.79056676, -0.60713384],
       [-0.91013178,  1.56100127,  0.09453718, -0.26293626],
       [ 1.22353034, -1.39566492, -0.02244134,  1.52808094]])

ikki boshqa boshqa ismga mos keluvchi malumotlarni qanday ajratib olardik

In [23]:
print(names)
print(data)

['Jasur' 'Doston' 'Habib' 'Ikrom' 'Jasur' 'Sardor' 'Jamshid']
[[-0.37496467  0.67438124  0.28814237 -0.6230284 ]
 [-0.95914298 -0.3807025   0.51446469  1.33437546]
 [-0.90967151  0.21212172  0.09479158  1.49019764]
 [ 0.51971308  2.5688994   0.79056676 -0.60713384]
 [ 0.3093182  -1.07644966  0.40523114  0.54613115]
 [-0.91013178  1.56100127  0.09453718 -0.26293626]
 [ 1.22353034 -1.39566492 -0.02244134  1.52808094]]


In [44]:
two_bool = (names == 'Jasur') | (names == 'Ikrom') # (|) yoki 
two_bool

array([ True, False, False,  True,  True, False, False])

In [45]:
data[two_bool] # Jasur va Ikromlarga tegishli malumotlarmi ajratib olish

array([[-0.37496467,  0.67438124,  0.28814237, -0.6230284 ],
       [ 0.51971308,  2.5688994 ,  0.79056676, -0.60713384],
       [ 0.3093182 , -1.07644966,  0.40523114,  0.54613115]])

Boolean indekslash juda ham foydali hisoblanadi. Ayniqsa masking indekslashda juda juda qol keladi, buni nafaqat string korinishidagi malumotlar ustida, balki raqamli malumotlarda ham ishlatilsa boladi


In [46]:
data

array([[-0.37496467,  0.67438124,  0.28814237, -0.6230284 ],
       [-0.95914298, -0.3807025 ,  0.51446469,  1.33437546],
       [-0.90967151,  0.21212172,  0.09479158,  1.49019764],
       [ 0.51971308,  2.5688994 ,  0.79056676, -0.60713384],
       [ 0.3093182 , -1.07644966,  0.40523114,  0.54613115],
       [-0.91013178,  1.56100127,  0.09453718, -0.26293626],
       [ 1.22353034, -1.39566492, -0.02244134,  1.52808094]])

Etibor bersangiz bizda manfiy qiymatlar bor, biz ularning qiymatlarin nolga ozgartirib qoyaylik

In [47]:
data[data<0] # indeksda bunday yozilishi, nolgan kichgina barcha elemenlarning indeksi chiqaradi

array([-0.37496467, -0.6230284 , -0.95914298, -0.3807025 , -0.90967151,
       -0.60713384, -1.07644966, -0.91013178, -0.26293626, -1.39566492,
       -0.02244134])

In [49]:
data[data<0] = 0 # shu elementlarni barchasini nolga tenglaymiz 
data

array([[0.        , 0.67438124, 0.28814237, 0.        ],
       [0.        , 0.        , 0.51446469, 1.33437546],
       [0.        , 0.21212172, 0.09479158, 1.49019764],
       [0.51971308, 2.5688994 , 0.79056676, 0.        ],
       [0.3093182 , 0.        , 0.40523114, 0.54613115],
       [0.        , 1.56100127, 0.09453718, 0.        ],
       [1.22353034, 0.        , 0.        , 1.52808094]])

In [50]:
data[data>0]

array([0.67438124, 0.28814237, 0.51446469, 1.33437546, 0.21212172,
       0.09479158, 1.49019764, 0.51971308, 2.5688994 , 0.79056676,
       0.3093182 , 0.40523114, 0.54613115, 1.56100127, 0.09453718,
       1.22353034, 1.52808094])

In [51]:
data[data>0] = 11 # shu elementlarni barchasini 11 tenglaymiz 
data

array([[ 0., 11., 11.,  0.],
       [ 0.,  0., 11., 11.],
       [ 0., 11., 11., 11.],
       [11., 11., 11.,  0.],
       [11.,  0., 11., 11.],
       [ 0., 11., 11.,  0.],
       [11.,  0.,  0., 11.]])

Xulosa qilib aytadigan bolsak boolean indekslash bizga massivlashning bir qancha malumotlari ustida bir vaqtning ozida turli xil amallarni barajarish imkoniyatlarini beradi