<a href="https://colab.research.google.com/github/jfcoderx/Data-Sciense/blob/main/5_Transposing%26Swapping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Massivlar pozitsiyasisni ko'chirish Transpose Va o'qalarini o'rnini almashtirish Swapping axes

Transpose <br>
chiziqli algebraning konsepsiyasi hisoblanadi. Chiziqli algebrada massivlarni ko'paytirishda ishlatiladi.<br>

Juda sodda tushuncha, shunchaki qator elementlarin ustun elementlariga ko'chirib qo'yish <br>
<br>A MASSIV<br>
(0,0) (0,1) <br>
(1,0) (1,1) <br>
(2,0) (2,1) --> (3,2) <br>
TRANSPOSE<br>
(0,0) (1,0) (2,0) <br>
(0,1) (1,1) (2,1) --> (2,3)<br>
<br>A MASSIV<br>
0 - 1 <br>
2 - 3 <br>
4 - 5 <br>
TRANSPOSE<br>
0 - 2 - 4 <br>
1 - 3 - 5<br>
<br>



In [1]:
import numpy as np

In [2]:
a_massiv = np.array([[0, 1], [2, 3], [4, 5]])
a_massiv

array([[0, 1],
       [2, 3],
       [4, 5]])

buni boshqacha usulda yaratish uchun RESHAPE metodidan

In [5]:
A = np.arange(6).reshape(3, 2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

TRANSPOSE

In [6]:
A.T # A massivning Transpose ko'rinishi

array([[0, 2, 4],
       [1, 3, 5]])

SWAPPING AXES, massivning oqlarini ornini almashtirish <br>
swapping axes, transpose bilan bir xil <br>
birdan bir farqi, transpose uzogi 2 o'lchamli massivlar<br>
swapping axes da esa istalgan o'lchamli massivning istalgancha o'qlarini almashtira olamiz


In [7]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

0, 1 boylab yonalgan o'q 0-o'q <br>
0, 2, 4 boylab yonalgan o'q 1-o'q <br>
shu uchun (0,1) oqlarni (1, 0) ga aylantiriladi

In [8]:
A.swapaxes(1, 0) # A massivimizning Transpose ko'rinishini beradi

array([[0, 2, 4],
       [1, 3, 5]])

Xulosa qilib aytsak, traspose swapaxesning bir xususiy holi hisoblandi

Transpose tushunchasi chiziqli algebrada qollanilaadigan tushuncha hisoblanadi <br>
A A^T bu kabi formulalarni korish mumkin <br>
bu A massivni A massivning Trasposega kopaytmasi degani


Kopaytirishimiz uchun numpy kutubxonasining, <br>
DOT() funksiyasidan foydalanmiz <br>
bu funksiya bir turdagi massivni ikkinchi turga kopaytirishda ishlatiladi

In [10]:
np.dot(A, A.T) # A A^T kopaytmasidan hosil bolgan massiv 

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])