<a href="https://colab.research.google.com/github/jfcoderx/Data-Sciense/blob/main/8_Mantiqiy_shart.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Massivga yo'naltirilgan dasturlash

### Mantiqiy shart operatorlarni massiv operator sifatida qollash

### Shart operoti sifatida WHERE dan foydalanish

### Misol
Ikta malumotlar (massivlar) mavjud: XARR va YARR <br>
Bizda shart mavjud, undagi elementlar soni XARR va YARR elementlar soni bilan bir xil <br>
Agarda shart TRUE ni qanoatlantirsa XARR ni 
aksincha holda YARR elementlarini qabul qilgan yangi massiv hosil qilinsin

In [1]:
import numpy as np

In [2]:
# Massivlar
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [3]:
# Shart
cond = np.array([True, False, True, True, False]) # o'zimiz shunday kiritganmiz
# demak cond elementi True bolsa shu elementga mos xarr elementini qabul qilamiz
# agar False bolsa shunga mos yarr elementini qabul qilamiz

In [7]:
# where
arr_con = np.where(cond, xarr, yarr) # cond==True : xarr elementi, cond==False : yarr elementi
arr_con

array([1.1, 2.2, 1.3, 1.4, 2.5])

Demak where uchun biz conditionlar yani shartlar toplami berdik va shu shartlar toplamiga mos massivlar berdik va yangi massiv hosil qilishimizda shu shartlar ketma ketligiga qara dedik, yani agar True bolsa xarr ni elementini ol dedik indeksiga mos ravishda, agar False bolsa yarr ni elementini ol dedik indeksiga mos ravishda, shunday saralab yangi massiv hosil qilib oldik

Yanayam yaxshiroq tushunish uchun taxminiy massiv yaratib olamiz


In [5]:
arr = np.random.randn(4, 4) # (4, 4) shakldagi taxminiy massivimiz
arr

array([[ 0.31530286,  0.82880682,  1.34274546, -0.24864411],
       [ 1.37945235, -0.17801993,  0.8760194 ,  1.35168082],
       [-0.38186925, -0.04386819,  0.64249937,  0.31314123],
       [-0.88864974, -0.35459929,  0.12660396,  0.53034137]])

barcha manfiy elementlarini -2 ga, barcha musbat elementlarni 2ga tenglab qoyaylik, bundan where bilan ham bajarsak boladi

In [6]:
# where
arr_wh = np.where(arr>0, 2, -2) # agar arr elementi musbat bolsa 2 olinadi arr_wh elementiga aylanadi, manfiy bolsa -2 elemtiga aylanadi joylari mos ravishda
arr_wh

array([[ 2,  2,  2, -2],
       [ 2, -2,  2,  2],
       [-2, -2,  2,  2],
       [-2, -2,  2,  2]])

Bu holda ham bizdagi massivlar elementlarini ozgartirishda yani uni ustida amal bajarishda wheredan foydalandik, agar massivimiz elementi musbat bolsa unda biz birginga elementini korsatdik yani 2ni, shu elementi ol dedik, agar manfiy bolsa unda -2 elementni ol dedik va ular ketma ketligidan massiv hosil qildik

Xulosa qilib aytadigan bolsak shart operatorlarida WHERE funksiyasi juda qol keladi