## Malumotlar tahlili. NumPy

### Fayllar bilan ishlash
NumPyda yaratilgan malumotlarni FAYLda saqlashni organamiz, dasturlash davomida turli ozgarishlar yaratamiz, bu ozgaruvchilarga ishlov beramiz, kelajakda ulardan foydalanish uchun ularni biror bir faylga saqlab qoyishimiz lozim

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Bu arr saqlash uchun save metodidan foydalanamiz <br>
arr.save berilgan arrni IKKILIK sanoq sistemasida saqlaydi <br>
arr.savetxt berilgan arrni TEXT korinishida saqlaydi <br>
bular bitta arr ni saqlash uchun bolsa<br>

savez, savez_compressed lar esa bir nechta arr larni saqlash uchun ishlatiladi

In [3]:
np.save('data', arr) # bunda fayl nomi = data.npy numpy fayllar shunday saqlanadi, yozmasak ozi default holatida saqlab ketadi, keyin saqlamoqchi bolgan arr nomi

bu fayldan oqimoqchi bolsak LOAD metodini chaqiramiz va fayl nomini beramiz va chaqirayotgan arr mizni qaysidir ozgaruvchiga saqlashimiz kerak

In [4]:
arr2 = np.load('data.npy')
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr1 = np.arange(20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Bir nechta arraylarni saqlashimiz uchun esa SAVEZ dan foydalanamiz

In [6]:
np.savez('arrays', arr1=arr1, arr2=arr2)

bu .npz formatda saqlanadi, arr1=arr1 qilganizmi arr1 nomini biz kalit soz sifatida kiritib ketdik

In [7]:
arrays = np.load('arrays.npz')

In [10]:
arrays['arr1']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
arrays['arr2']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arrays

savez bilan savez_compressed farqi birinchisida malumotlar siqilinmaydi, ikkinchisida siqilinadi, ayniqsa juda katta fayllarda siqish joyni tejashga olib keladi

In [14]:
np.savez_compressed('array_comp', ar1=arr1, ar2=arr2)

In [15]:
arrays_compressed = np.load('array_comp.npz')

In [16]:
arrays_compressed['ar1']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
arrays_compressed['ar2']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])